(define (problem marketcount5)
(:domain Trader)
(:objects
              Thule Tartu Daugavpils Kaunas    Sough  - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Thule)    2.8)
        (= (on-sale Food Thule)  18)
        (= (price ExpensiveRugs Thule)    5.6)
        (= (on-sale ExpensiveRugs Thule)  16)
        (= (price Coffee Thule)    18.8)
        (= (on-sale Coffee Thule)  20)
        (= (price Cattle Thule)    4.0)
        (= (on-sale Cattle Thule)  0)
        (= (price Water Thule)    21.2)
        (= (on-sale Water Thule)  25)
        (= (price Cars Thule)    97.6)
        (= (on-sale Cars Thule)  6)
        (= (price GummyBears Thule)    61.2)
        (= (on-sale GummyBears Thule)  26)
        (= (price Computers Thule)    95.2)
        (= (on-sale Computers Thule)  0)
        (= (price LaminateFloor Thule)    61.2)
        (= (on-sale LaminateFloor Thule)  4)
        (= (price Copper Thule)    33.6)
        (= (on-sale Copper Thule)  11)
        (= (price Footballs Thule)    80.8)
        (= (on-sale Footballs Thule)  0)
        (= (price Kittens  Thule)    48.8)
        (= (on-sale Kittens  Thule)  18)
        (= (price Minerals Thule)    10.3)
        (= (on-sale Minerals Thule)  59)
        (= (price Gold  Thule)    36.3)
        (= (on-sale Gold  Thule)  8)
        (= (price Platinum Thule)    63.6)
        (= (on-sale Platinum Thule)  3)
        (= (price DVDs Thule)    15.6)
        (= (on-sale DVDs Thule)  0)
        (= (price TuringMachines Thule)    57.2)
        (= (on-sale TuringMachines Thule)  0)

        (= (price Food Tartu)    3.6)
        (= (on-sale Food Tartu)  16)
        (= (price ExpensiveRugs Tartu)    6.0)
        (= (on-sale ExpensiveRugs Tartu)  15)
        (= (price Coffee Tartu)    20.0)
        (= (on-sale Coffee Tartu)  17)
        (= (price Cattle Tartu)    6.0)
        (= (on-sale Cattle Tartu)  0)
        (= (price Water Tartu)    23.2)
        (= (on-sale Water Tartu)  20)
        (= (price Cars Tartu)    94.3)
        (= (on-sale Cars Tartu)  14)
        (= (price GummyBears Tartu)    49.6)
        (= (on-sale GummyBears Tartu)  55)
        (= (price Computers Tartu)    89.6)
        (= (on-sale Computers Tartu)  0)
        (= (price LaminateFloor Tartu)    58.8)
        (= (on-sale LaminateFloor Tartu)  10)
        (= (price Copper Tartu)    33.2)
        (= (on-sale Copper Tartu)  12)
        (= (price Footballs Tartu)    75.6)
        (= (on-sale Footballs Tartu)  0)
        (= (price Kittens  Tartu)    52.3)
        (= (on-sale Kittens  Tartu)  9)
        (= (price Minerals Tartu)    10.8)
        (= (on-sale Minerals Tartu)  58)
        (= (price Gold  Tartu)    36.8)
        (= (on-sale Gold  Tartu)  7)
        (= (price Platinum Tartu)    64.3)
        (= (on-sale Platinum Tartu)  1)
        (= (price DVDs Tartu)    16.0)
        (= (on-sale DVDs Tartu)  0)
        (= (price TuringMachines Tartu)    51.2)
        (= (on-sale TuringMachines Tartu)  0)

        (= (price Food Daugavpils)    4.3)
        (= (on-sale Food Daugavpils)  14)
        (= (price ExpensiveRugs Daugavpils)    6.3)
        (= (on-sale ExpensiveRugs Daugavpils)  14)
        (= (price Coffee Daugavpils)    21.2)
        (= (on-sale Coffee Daugavpils)  14)
        (= (price Cattle Daugavpils)    8.0)
        (= (on-sale Cattle Daugavpils)  0)
        (= (price Water Daugavpils)    25.2)
        (= (on-sale Water Daugavpils)  15)
        (= (price Cars Daugavpils)    91.2)
        (= (on-sale Cars Daugavpils)  22)
        (= (price GummyBears Daugavpils)    38.0)
        (= (on-sale GummyBears Daugavpils)  0)
        (= (price Computers Daugavpils)    84.0)
        (= (on-sale Computers Daugavpils)  0)
        (= (price LaminateFloor Daugavpils)    56.3)
        (= (on-sale LaminateFloor Daugavpils)  16)
        (= (price Copper Daugavpils)    32.8)
        (= (on-sale Copper Daugavpils)  13)
        (= (price Footballs Daugavpils)    70.3)
        (= (on-sale Footballs Daugavpils)  0)
        (= (price Kittens Daugavpils)    56.0)
        (= (on-sale Kittens Daugavpils)  0)
        (= (price Minerals Daugavpils)    11.2)
        (= (on-sale Minerals Daugavpils)  57)
        (= (price Gold Daugavpils)    37.2)
        (= (on-sale Gold Daugavpils)  6)
        (= (price Platinum Daugavpils)    65.2)
        (= (on-sale Platinum Daugavpils)  63)
        (= (price DVDs Daugavpils)    16.3)
        (= (on-sale DVDs Daugavpils)  0)
        (= (price TuringMachines Daugavpils)    45.2)
        (= (on-sale TuringMachines Daugavpils)  0)

        (= (price Food Kaunas)    2.0)
        (= (on-sale Food Kaunas)  20)
        (= (price ExpensiveRugs Kaunas)    5.2)
        (= (on-sale ExpensiveRugs Kaunas)  17)
        (= (price Coffee Kaunas)    17.6)
        (= (on-sale Coffee Kaunas)  23)
        (= (price Cattle Kaunas)    2.0)
        (= (on-sale Cattle Kaunas)  5)
        (= (price Water Kaunas)    19.2)
        (= (on-sale Water Kaunas)  30)
        (= (price Cars Kaunas)    100.8)
        (= (on-sale Cars Kaunas)  0)
        (= (price GummyBears Kaunas)    72.8)
        (= (on-sale GummyBears Kaunas)  61)
        (= (price Computers Kaunas)    100.8)
        (= (on-sale Computers Kaunas)  0)
        (= (price LaminateFloor Kaunas)    63.6)
        (= (on-sale LaminateFloor Kaunas)  0)
        (= (price Copper Kaunas)    34.0)
        (= (on-sale Copper Kaunas)  10)
        (= (price Footballs Kaunas)    86.0)
        (= (on-sale Footballs Kaunas)  0)
        (= (price Kittens Kaunas)    45.2)
        (= (on-sale Kittens Kaunas)  27)
        (= (price Minerals Kaunas)    10.0)
        (= (on-sale Minerals Kaunas)  60)
        (= (price Gold Kaunas)    36.0)
        (= (on-sale Gold Kaunas)  9)
        (= (price Platinum Kaunas)    62.8)
        (= (on-sale Platinum Kaunas)  5)
        (= (price DVDs Kaunas)    15.2)
        (= (on-sale DVDs Kaunas)  1)
        (= (price TuringMachines Kaunas)    63.2)
        (= (on-sale TuringMachines Kaunas)  0)

        (= (price Food Sough)    5.2)
        (= (on-sale Food Sough)  12)
        (= (price ExpensiveRugs Sough)    6.8)
        (= (on-sale ExpensiveRugs Sough)  13)
        (= (price Coffee Sough)    22.3)
        (= (on-sale Coffee Sough)  11)
        (= (price Cattle Sough)    10.0)
        (= (on-sale Cattle Sough)  0)
        (= (price Water Sough)    27.2)
        (= (on-sale Water Sough)  10)
        (= (price Cars Sough)    88.0)
        (= (on-sale Cars Sough)  30)
        (= (price GummyBears Sough)    26.3)
        (= (on-sale GummyBears Sough)  0)
        (= (price Computers Sough)    78.3)
        (= (on-sale Computers Sough)  14)
        (= (price LaminateFloor Sough)    54.0)
        (= (on-sale LaminateFloor Sough)  22)
        (= (price Copper Sough)    32.3)
        (= (on-sale Copper Sough)  14)
        (= (price Footballs Sough)    65.2)
        (= (on-sale Footballs Sough)  0)
        (= (price Kittens Sough)    59.6)
        (= (on-sale Kittens Sough)  0)
        (= (price Minerals Sough)    11.6)
        (= (on-sale Minerals Sough)  56)
        (= (price Gold Sough)    37.6)
        (= (on-sale Gold Sough)  5)
        (= (price Platinum Sough)    66.0)
        (= (on-sale Platinum Sough)  61)
        (= (price DVDs Sough)    16.8)
        (= (on-sale DVDs Sough)  0)
        (= (price TuringMachines Sough)    39.2)
        (= (on-sale TuringMachines Sough)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Thule Tartu ) 0.8)
        (= (drive-cost Tartu Thule ) 0.8)
        (can-drive Thule Tartu)
        (can-drive Tartu Thule)
        (= (drive-cost Thule Daugavpils ) 6.3)
        (= (drive-cost Daugavpils Thule ) 6.3)
        (can-drive Thule Daugavpils)
        (can-drive Daugavpils Thule)
        (= (drive-cost Thule Kaunas ) 5.9)
        (= (drive-cost Kaunas Thule ) 5.9)
        (can-drive Thule Kaunas)
        (can-drive Kaunas Thule)
        (= (drive-cost Thule Sough ) 4.9)
        (= (drive-cost Sough Thule ) 4.9)
        (can-drive Thule Sough)
        (can-drive Sough Thule)
        (= (drive-cost Tartu Daugavpils ) 5.7)
        (= (drive-cost Daugavpils Tartu ) 5.7)
        (can-drive Tartu Daugavpils)
        (can-drive Daugavpils Tartu)
        (= (drive-cost Tartu Kaunas ) 6.7)
        (= (drive-cost Kaunas Tartu ) 6.7)
        (can-drive Tartu Kaunas)
        (can-drive Kaunas Tartu)
        (= (drive-cost Tartu Sough ) 4.1)
        (= (drive-cost Sough Tartu ) 4.1)
        (can-drive Tartu Sough)
        (can-drive Sough Tartu)
        (= (drive-cost Daugavpils Sough ) 3.9)
        (= (drive-cost Sough Daugavpils ) 3.9)
        (can-drive Daugavpils Sough)
        (can-drive Sough Daugavpils)
        (at camel0      Sough)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
