(define (problem marketcount5)
(:domain Trader)
(:objects
            Ogre Tukums Viljandi Cesis Salaspils  - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Ogre)    6.8)
        (= (on-sale Food Ogre)  8)
        (= (price ExpensiveRugs Ogre)    7.6)
        (= (on-sale ExpensiveRugs Ogre)  11)
        (= (price Coffee Ogre)    24.8)
        (= (on-sale Coffee Ogre)  5)
        (= (price Cattle Ogre)    14.0)
        (= (on-sale Cattle Ogre)  0)
        (= (price Water Ogre)    31.2)
        (= (on-sale Water Ogre)  0)
        (= (price Cars Ogre)    81.6)
        (= (on-sale Cars Ogre)  46)
        (= (price GummyBears Ogre)    3.2)
        (= (on-sale GummyBears Ogre)  0)
        (= (price Computers Ogre)    67.2)
        (= (on-sale Computers Ogre)  42)
        (= (price LaminateFloor Ogre)    49.2)
        (= (on-sale LaminateFloor Ogre)  34)
        (= (price Copper Ogre)    31.6)
        (= (on-sale Copper Ogre)  16)
        (= (price Footballs Ogre)    54.8)
        (= (on-sale Footballs Ogre)  16)
        (= (price Kittens Ogre)    66.8)
        (= (on-sale Kittens Ogre)  0)
        (= (price Minerals Ogre)    12.3)
        (= (on-sale Minerals Ogre)  54)
        (= (price Gold Ogre)    38.3)
        (= (on-sale Gold Ogre)  3)
        (= (price Platinum Ogre)    67.6)
        (= (on-sale Platinum Ogre)  57)
        (= (price DVDs Ogre)    17.6)
        (= (on-sale DVDs Ogre)  0)
        (= (price TuringMachines Ogre)    27.2)
        (= (on-sale TuringMachines Ogre)  0)

        (= (price Food Tukums)    7.6)
        (= (on-sale Food Tukums)  6)
        (= (price ExpensiveRugs Tukums)    8.0)
        (= (on-sale ExpensiveRugs Tukums)  10)
        (= (price Coffee Tukums)    26.0)
        (= (on-sale Coffee Tukums)  2)
        (= (price Cattle Tukums)    16.0)
        (= (on-sale Cattle Tukums)  0)
        (= (price Water Tukums)    33.2)
        (= (on-sale Water Tukums)  0)
        (= (price Cars Tukums)    78.3)
        (= (on-sale Cars Tukums)  54)
        (= (price GummyBears Tukums)    94.0)
        (= (on-sale GummyBears Tukums)  8)
        (= (price Computers Tukums)    61.6)
        (= (on-sale Computers Tukums)  56)
        (= (price LaminateFloor Tukums)    46.8)
        (= (on-sale LaminateFloor Tukums)  40)
        (= (price Copper Tukums)    31.2)
        (= (on-sale Copper Tukums)  17)
        (= (price Footballs Tukums)    49.6)
        (= (on-sale Footballs Tukums)  29)
        (= (price Kittens Tukums)    70.3)
        (= (on-sale Kittens Tukums)  0)
        (= (price Minerals Tukums)    12.8)
        (= (on-sale Minerals Tukums)  53)
        (= (price Gold Tukums)    38.8)
        (= (on-sale Gold Tukums)  2)
        (= (price Platinum Tukums)    68.3)
        (= (on-sale Platinum Tukums)  55)
        (= (price DVDs Tukums)    18.0)
        (= (on-sale DVDs Tukums)  0)
        (= (price TuringMachines Tukums)    21.2)
        (= (on-sale TuringMachines Tukums)  0)

        (= (price Food Viljandi)    6.8)
        (= (on-sale Food Viljandi)  8)
        (= (price ExpensiveRugs Viljandi)    7.6)
        (= (on-sale ExpensiveRugs Viljandi)  11)
        (= (price Coffee Viljandi)    24.8)
        (= (on-sale Coffee Viljandi)  5)
        (= (price Cattle Viljandi)    14.0)
        (= (on-sale Cattle Viljandi)  0)
        (= (price Water Viljandi)    31.2)
        (= (on-sale Water Viljandi)  0)
        (= (price Cars Viljandi)    81.6)
        (= (on-sale Cars Viljandi)  46)
        (= (price GummyBears Viljandi)    3.2)
        (= (on-sale GummyBears Viljandi)  0)
        (= (price Computers Viljandi)    67.2)
        (= (on-sale Computers Viljandi)  42)
        (= (price LaminateFloor Viljandi)    49.2)
        (= (on-sale LaminateFloor Viljandi)  34)
        (= (price Copper Viljandi)    31.6)
        (= (on-sale Copper Viljandi)  16)
        (= (price Footballs Viljandi)    54.8)
        (= (on-sale Footballs Viljandi)  16)
        (= (price Kittens Viljandi)    66.8)
        (= (on-sale Kittens Viljandi)  0)
        (= (price Minerals Viljandi)    12.3)
        (= (on-sale Minerals Viljandi)  54)
        (= (price Gold Viljandi)    38.3)
        (= (on-sale Gold Viljandi)  3)
        (= (price Platinum Viljandi)    67.6)
        (= (on-sale Platinum Viljandi)  57)
        (= (price DVDs Viljandi)    17.6)
        (= (on-sale DVDs Viljandi)  0)
        (= (price TuringMachines Viljandi)    27.2)
        (= (on-sale TuringMachines Viljandi)  0)

        (= (price Food Cesis)    6.0)
        (= (on-sale Food Cesis)  10)
        (= (price ExpensiveRugs Cesis)    7.2)
        (= (on-sale ExpensiveRugs Cesis)  12)
        (= (price Coffee Cesis)    23.6)
        (= (on-sale Coffee Cesis)  8)
        (= (price Cattle Cesis)    12.0)
        (= (on-sale Cattle Cesis)  0)
        (= (price Water Cesis)    29.2)
        (= (on-sale Water Cesis)  5)
        (= (price Cars Cesis)    84.8)
        (= (on-sale Cars Cesis)  38)
        (= (price GummyBears Cesis)    14.8)
        (= (on-sale GummyBears Cesis)  0)
        (= (price Computers Cesis)    72.8)
        (= (on-sale Computers Cesis)  28)
        (= (price LaminateFloor Cesis)    51.6)
        (= (on-sale LaminateFloor Cesis)  28)
        (= (price Copper Cesis)    32.0)
        (= (on-sale Copper Cesis)  15)
        (= (price Footballs Cesis)    60.0)
        (= (on-sale Footballs Cesis)  3)
        (= (price Kittens Cesis)    63.2)
        (= (on-sale Kittens Cesis)  0)
        (= (price Minerals Cesis)    12.0)
        (= (on-sale Minerals Cesis)  55)
        (= (price Gold Cesis)    38.0)
        (= (on-sale Gold Cesis)  4)
        (= (price Platinum Cesis)    66.8)
        (= (on-sale Platinum Cesis)  59)
        (= (price DVDs Cesis)    17.2)
        (= (on-sale DVDs Cesis)  0)
        (= (price TuringMachines Cesis)    33.2)
        (= (on-sale TuringMachines Cesis)  0)

        (= (price Food Salaspils)    2.0)
        (= (on-sale Food Salaspils)  20)
        (= (price ExpensiveRugs Salaspils)    5.2)
        (= (on-sale ExpensiveRugs Salaspils)  17)
        (= (price Coffee Salaspils)    17.6)
        (= (on-sale Coffee Salaspils)  23)
        (= (price Cattle Salaspils)    2.0)
        (= (on-sale Cattle Salaspils)  5)
        (= (price Water Salaspils)    19.2)
        (= (on-sale Water Salaspils)  30)
        (= (price Cars Salaspils)    100.8)
        (= (on-sale Cars Salaspils)  0)
        (= (price GummyBears Salaspils)    72.8)
        (= (on-sale GummyBears Salaspils)  61)
        (= (price Computers Salaspils)    100.8)
        (= (on-sale Computers Salaspils)  0)
        (= (price LaminateFloor Salaspils)    63.6)
        (= (on-sale LaminateFloor Salaspils)  0)
        (= (price Copper Salaspils)    34.0)
        (= (on-sale Copper Salaspils)  10)
        (= (price Footballs Salaspils)    86.0)
        (= (on-sale Footballs Salaspils)  0)
        (= (price Kittens Salaspils)    45.2)
        (= (on-sale Kittens Salaspils)  27)
        (= (price Minerals Salaspils)    10.0)
        (= (on-sale Minerals Salaspils)  60)
        (= (price Gold Salaspils)    36.0)
        (= (on-sale Gold Salaspils)  9)
        (= (price Platinum Salaspils)    62.8)
        (= (on-sale Platinum Salaspils)  5)
        (= (price DVDs Salaspils)    15.2)
        (= (on-sale DVDs Salaspils)  1)
        (= (price TuringMachines Salaspils)    63.2)
        (= (on-sale TuringMachines Salaspils)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Ogre Tukums ) 3.1)
        (= (drive-cost Tukums Ogre ) 3.1)
        (can-drive Ogre Tukums)
        (can-drive Tukums Ogre)
        (= (drive-cost Ogre Viljandi ) 7.0)
        (= (drive-cost Viljandi Ogre ) 7.0)
        (can-drive Ogre Viljandi)
        (can-drive Viljandi Ogre)
        (= (drive-cost Ogre Cesis ) 6.9)
        (= (drive-cost Cesis Ogre ) 6.9)
        (can-drive Ogre Cesis)
        (can-drive Cesis Ogre)
        (= (drive-cost Ogre Salaspils ) 6.8)
        (= (drive-cost Salaspils Ogre ) 6.8)
        (can-drive Ogre Salaspils)
        (can-drive Salaspils Ogre)
        (= (drive-cost Tukums Salaspils ) 4.6)
        (= (drive-cost Salaspils Tukums ) 4.6)
        (can-drive Tukums Salaspils)
        (can-drive Salaspils Tukums)
        (at camel0     Salaspils)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
