(define (problem marketcount5)
(:domain Trader)
(:objects
          Riga Oslo Hamburg Torshavn  Longyearbyen  - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Riga)    2.0)
        (= (on-sale Food Riga)  20)
        (= (price ExpensiveRugs Riga)    5.2)
        (= (on-sale ExpensiveRugs Riga)  17)
        (= (price Coffee Riga)    17.6)
        (= (on-sale Coffee Riga)  23)
        (= (price Cattle Riga)    2.0)
        (= (on-sale Cattle Riga)  5)
        (= (price Water Riga)    19.2)
        (= (on-sale Water Riga)  30)
        (= (price Cars Riga)    100.8)
        (= (on-sale Cars Riga)  0)
        (= (price GummyBears Riga)    72.8)
        (= (on-sale GummyBears Riga)  61)
        (= (price Computers Riga)    100.8)
        (= (on-sale Computers Riga)  0)
        (= (price LaminateFloor Riga)    63.6)
        (= (on-sale LaminateFloor Riga)  0)
        (= (price Copper Riga)    34.0)
        (= (on-sale Copper Riga)  10)
        (= (price Footballs Riga)    86.0)
        (= (on-sale Footballs Riga)  0)
        (= (price Kittens Riga)    45.2)
        (= (on-sale Kittens Riga)  27)
        (= (price Minerals Riga)    10.0)
        (= (on-sale Minerals Riga)  60)
        (= (price Gold Riga)    36.0)
        (= (on-sale Gold Riga)  9)
        (= (price Platinum Riga)    62.8)
        (= (on-sale Platinum Riga)  5)
        (= (price DVDs Riga)    15.2)
        (= (on-sale DVDs Riga)  1)
        (= (price TuringMachines Riga)    63.2)
        (= (on-sale TuringMachines Riga)  0)

        (= (price Food Oslo)    4.3)
        (= (on-sale Food Oslo)  14)
        (= (price ExpensiveRugs Oslo)    6.3)
        (= (on-sale ExpensiveRugs Oslo)  14)
        (= (price Coffee Oslo)    21.2)
        (= (on-sale Coffee Oslo)  14)
        (= (price Cattle Oslo)    8.0)
        (= (on-sale Cattle Oslo)  0)
        (= (price Water Oslo)    25.2)
        (= (on-sale Water Oslo)  15)
        (= (price Cars Oslo)    91.2)
        (= (on-sale Cars Oslo)  22)
        (= (price GummyBears Oslo)    38.0)
        (= (on-sale GummyBears Oslo)  0)
        (= (price Computers Oslo)    84.0)
        (= (on-sale Computers Oslo)  0)
        (= (price LaminateFloor Oslo)    56.3)
        (= (on-sale LaminateFloor Oslo)  16)
        (= (price Copper Oslo)    32.8)
        (= (on-sale Copper Oslo)  13)
        (= (price Footballs Oslo)    70.3)
        (= (on-sale Footballs Oslo)  0)
        (= (price Kittens Oslo)    56.0)
        (= (on-sale Kittens Oslo)  0)
        (= (price Minerals Oslo)    11.2)
        (= (on-sale Minerals Oslo)  57)
        (= (price Gold Oslo)    37.2)
        (= (on-sale Gold Oslo)  6)
        (= (price Platinum Oslo)    65.2)
        (= (on-sale Platinum Oslo)  63)
        (= (price DVDs Oslo)    16.3)
        (= (on-sale DVDs Oslo)  0)
        (= (price TuringMachines Oslo)    45.2)
        (= (on-sale TuringMachines Oslo)  0)

        (= (price Food Hamburg)    2.8)
        (= (on-sale Food Hamburg)  18)
        (= (price ExpensiveRugs Hamburg)    5.6)
        (= (on-sale ExpensiveRugs Hamburg)  16)
        (= (price Coffee Hamburg)    18.8)
        (= (on-sale Coffee Hamburg)  20)
        (= (price Cattle Hamburg)    4.0)
        (= (on-sale Cattle Hamburg)  0)
        (= (price Water Hamburg)    21.2)
        (= (on-sale Water Hamburg)  25)
        (= (price Cars Hamburg)    97.6)
        (= (on-sale Cars Hamburg)  6)
        (= (price GummyBears Hamburg)    61.2)
        (= (on-sale GummyBears Hamburg)  26)
        (= (price Computers Hamburg)    95.2)
        (= (on-sale Computers Hamburg)  0)
        (= (price LaminateFloor Hamburg)    61.2)
        (= (on-sale LaminateFloor Hamburg)  4)
        (= (price Copper Hamburg)    33.6)
        (= (on-sale Copper Hamburg)  11)
        (= (price Footballs Hamburg)    80.8)
        (= (on-sale Footballs Hamburg)  0)
        (= (price Kittens Hamburg)    48.8)
        (= (on-sale Kittens Hamburg)  18)
        (= (price Minerals Hamburg)    10.3)
        (= (on-sale Minerals Hamburg)  59)
        (= (price Gold Hamburg)    36.3)
        (= (on-sale Gold Hamburg)  8)
        (= (price Platinum Hamburg)    63.6)
        (= (on-sale Platinum Hamburg)  3)
        (= (price DVDs Hamburg)    15.6)
        (= (on-sale DVDs Hamburg)  0)
        (= (price TuringMachines Hamburg)    57.2)
        (= (on-sale TuringMachines Hamburg)  0)

        (= (price Food Torshavn)    2.0)
        (= (on-sale Food Torshavn)  20)
        (= (price ExpensiveRugs Torshavn)    5.2)
        (= (on-sale ExpensiveRugs Torshavn)  17)
        (= (price Coffee Torshavn)    17.6)
        (= (on-sale Coffee Torshavn)  23)
        (= (price Cattle Torshavn)    2.0)
        (= (on-sale Cattle Torshavn)  5)
        (= (price Water Torshavn)    19.2)
        (= (on-sale Water Torshavn)  30)
        (= (price Cars Torshavn)    100.8)
        (= (on-sale Cars Torshavn)  0)
        (= (price GummyBears Torshavn)    72.8)
        (= (on-sale GummyBears Torshavn)  61)
        (= (price Computers Torshavn)    100.8)
        (= (on-sale Computers Torshavn)  0)
        (= (price LaminateFloor Torshavn)    63.6)
        (= (on-sale LaminateFloor Torshavn)  0)
        (= (price Copper Torshavn)    34.0)
        (= (on-sale Copper Torshavn)  10)
        (= (price Footballs Torshavn)    86.0)
        (= (on-sale Footballs Torshavn)  0)
        (= (price Kittens Torshavn)    45.2)
        (= (on-sale Kittens Torshavn)  27)
        (= (price Minerals Torshavn)    10.0)
        (= (on-sale Minerals Torshavn)  60)
        (= (price Gold Torshavn)    36.0)
        (= (on-sale Gold Torshavn)  9)
        (= (price Platinum Torshavn)    62.8)
        (= (on-sale Platinum Torshavn)  5)
        (= (price DVDs Torshavn)    15.2)
        (= (on-sale DVDs Torshavn)  1)
        (= (price TuringMachines Torshavn)    63.2)
        (= (on-sale TuringMachines Torshavn)  0)

        (= (price Food Longyearbyen)    7.6)
        (= (on-sale Food Longyearbyen)  6)
        (= (price ExpensiveRugs Longyearbyen)    8.0)
        (= (on-sale ExpensiveRugs Longyearbyen)  10)
        (= (price Coffee Longyearbyen)    26.0)
        (= (on-sale Coffee Longyearbyen)  2)
        (= (price Cattle Longyearbyen)    16.0)
        (= (on-sale Cattle Longyearbyen)  0)
        (= (price Water Longyearbyen)    33.2)
        (= (on-sale Water Longyearbyen)  0)
        (= (price Cars Longyearbyen)    78.3)
        (= (on-sale Cars Longyearbyen)  54)
        (= (price GummyBears Longyearbyen)    94.0)
        (= (on-sale GummyBears Longyearbyen)  8)
        (= (price Computers Longyearbyen)    61.6)
        (= (on-sale Computers Longyearbyen)  56)
        (= (price LaminateFloor Longyearbyen)    46.8)
        (= (on-sale LaminateFloor Longyearbyen)  40)
        (= (price Copper Longyearbyen)    31.2)
        (= (on-sale Copper Longyearbyen)  17)
        (= (price Footballs Longyearbyen)    49.6)
        (= (on-sale Footballs Longyearbyen)  29)
        (= (price Kittens Longyearbyen)    70.3)
        (= (on-sale Kittens Longyearbyen)  0)
        (= (price Minerals Longyearbyen)    12.8)
        (= (on-sale Minerals Longyearbyen)  53)
        (= (price Gold Longyearbyen)    38.8)
        (= (on-sale Gold Longyearbyen)  2)
        (= (price Platinum Longyearbyen)    68.3)
        (= (on-sale Platinum Longyearbyen)  55)
        (= (price DVDs Longyearbyen)    18.0)
        (= (on-sale DVDs Longyearbyen)  0)
        (= (price TuringMachines Longyearbyen)    21.2)
        (= (on-sale TuringMachines Longyearbyen)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Riga Oslo ) 6.1)
        (= (drive-cost Oslo Riga ) 6.1)
        (can-drive Riga Oslo)
        (can-drive Oslo Riga)
        (= (drive-cost Riga Hamburg ) 6.9)
        (= (drive-cost Hamburg Riga ) 6.9)
        (can-drive Riga Hamburg)
        (can-drive Hamburg Riga)
        (= (drive-cost Riga Torshavn ) 5.3)
        (= (drive-cost Torshavn Riga ) 5.3)
        (can-drive Riga Torshavn)
        (can-drive Torshavn Riga)
        (= (drive-cost Riga Longyearbyen ) 5.2)
        (= (drive-cost Longyearbyen Riga ) 5.2)
        (can-drive Riga Longyearbyen)
        (can-drive Longyearbyen Riga)
        (= (drive-cost Hamburg Longyearbyen ) 1.7)
        (= (drive-cost Longyearbyen Hamburg ) 1.7)
        (can-drive Hamburg Longyearbyen)
        (can-drive Longyearbyen Hamburg)
        (at camel0      Longyearbyen)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
