(define (problem marketcount5)
(:domain Trader)
(:objects
             Narva Oslo Jelgava  Jurmala   Valmiera  - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Narva)    5.2)
        (= (on-sale Food Narva)  12)
        (= (price ExpensiveRugs Narva)    6.8)
        (= (on-sale ExpensiveRugs Narva)  13)
        (= (price Coffee Narva)    22.3)
        (= (on-sale Coffee Narva)  11)
        (= (price Cattle Narva)    10.0)
        (= (on-sale Cattle Narva)  0)
        (= (price Water Narva)    27.2)
        (= (on-sale Water Narva)  10)
        (= (price Cars Narva)    88.0)
        (= (on-sale Cars Narva)  30)
        (= (price GummyBears Narva)    26.3)
        (= (on-sale GummyBears Narva)  0)
        (= (price Computers Narva)    78.3)
        (= (on-sale Computers Narva)  14)
        (= (price LaminateFloor Narva)    54.0)
        (= (on-sale LaminateFloor Narva)  22)
        (= (price Copper Narva)    32.3)
        (= (on-sale Copper Narva)  14)
        (= (price Footballs Narva)    65.2)
        (= (on-sale Footballs Narva)  0)
        (= (price Kittens Narva)    59.6)
        (= (on-sale Kittens Narva)  0)
        (= (price Minerals Narva)    11.6)
        (= (on-sale Minerals Narva)  56)
        (= (price Gold Narva)    37.6)
        (= (on-sale Gold Narva)  5)
        (= (price Platinum Narva)    66.0)
        (= (on-sale Platinum Narva)  61)
        (= (price DVDs Narva)    16.8)
        (= (on-sale DVDs Narva)  0)
        (= (price TuringMachines Narva)    39.2)
        (= (on-sale TuringMachines Narva)  0)

        (= (price Food Oslo)    4.3)
        (= (on-sale Food Oslo)  14)
        (= (price ExpensiveRugs Oslo)    6.3)
        (= (on-sale ExpensiveRugs Oslo)  14)
        (= (price Coffee Oslo)    21.2)
        (= (on-sale Coffee Oslo)  14)
        (= (price Cattle Oslo)    8.0)
        (= (on-sale Cattle Oslo)  0)
        (= (price Water Oslo)    25.2)
        (= (on-sale Water Oslo)  15)
        (= (price Cars Oslo)    91.2)
        (= (on-sale Cars Oslo)  22)
        (= (price GummyBears Oslo)    38.0)
        (= (on-sale GummyBears Oslo)  0)
        (= (price Computers Oslo)    84.0)
        (= (on-sale Computers Oslo)  0)
        (= (price LaminateFloor Oslo)    56.3)
        (= (on-sale LaminateFloor Oslo)  16)
        (= (price Copper Oslo)    32.8)
        (= (on-sale Copper Oslo)  13)
        (= (price Footballs Oslo)    70.3)
        (= (on-sale Footballs Oslo)  0)
        (= (price Kittens Oslo)    56.0)
        (= (on-sale Kittens Oslo)  0)
        (= (price Minerals Oslo)    11.2)
        (= (on-sale Minerals Oslo)  57)
        (= (price Gold Oslo)    37.2)
        (= (on-sale Gold Oslo)  6)
        (= (price Platinum Oslo)    65.2)
        (= (on-sale Platinum Oslo)  63)
        (= (price DVDs Oslo)    16.3)
        (= (on-sale DVDs Oslo)  0)
        (= (price TuringMachines Oslo)    45.2)
        (= (on-sale TuringMachines Oslo)  0)

        (= (price Food Jelgava)    6.8)
        (= (on-sale Food Jelgava)  8)
        (= (price ExpensiveRugs Jelgava)    7.6)
        (= (on-sale ExpensiveRugs Jelgava)  11)
        (= (price Coffee Jelgava)    24.8)
        (= (on-sale Coffee Jelgava)  5)
        (= (price Cattle Jelgava)    14.0)
        (= (on-sale Cattle Jelgava)  0)
        (= (price Water Jelgava)    31.2)
        (= (on-sale Water Jelgava)  0)
        (= (price Cars Jelgava)    81.6)
        (= (on-sale Cars Jelgava)  46)
        (= (price GummyBears Jelgava)    3.2)
        (= (on-sale GummyBears Jelgava)  0)
        (= (price Computers Jelgava)    67.2)
        (= (on-sale Computers Jelgava)  42)
        (= (price LaminateFloor Jelgava)    49.2)
        (= (on-sale LaminateFloor Jelgava)  34)
        (= (price Copper Jelgava)    31.6)
        (= (on-sale Copper Jelgava)  16)
        (= (price Footballs Jelgava)    54.8)
        (= (on-sale Footballs Jelgava)  16)
        (= (price Kittens Jelgava)    66.8)
        (= (on-sale Kittens Jelgava)  0)
        (= (price Minerals Jelgava)    12.3)
        (= (on-sale Minerals Jelgava)  54)
        (= (price Gold Jelgava)    38.3)
        (= (on-sale Gold Jelgava)  3)
        (= (price Platinum Jelgava)    67.6)
        (= (on-sale Platinum Jelgava)  57)
        (= (price DVDs Jelgava)    17.6)
        (= (on-sale DVDs Jelgava)  0)
        (= (price TuringMachines Jelgava)    27.2)
        (= (on-sale TuringMachines Jelgava)  0)

        (= (price Food Jurmala)    2.0)
        (= (on-sale Food Jurmala)  20)
        (= (price ExpensiveRugs Jurmala)    5.2)
        (= (on-sale ExpensiveRugs Jurmala)  17)
        (= (price Coffee Jurmala)    17.6)
        (= (on-sale Coffee Jurmala)  23)
        (= (price Cattle Jurmala)    2.0)
        (= (on-sale Cattle Jurmala)  5)
        (= (price Water Jurmala)    19.2)
        (= (on-sale Water Jurmala)  30)
        (= (price Cars Jurmala)    100.8)
        (= (on-sale Cars Jurmala)  0)
        (= (price GummyBears Jurmala)    72.8)
        (= (on-sale GummyBears Jurmala)  61)
        (= (price Computers Jurmala)    100.8)
        (= (on-sale Computers Jurmala)  0)
        (= (price LaminateFloor Jurmala)    63.6)
        (= (on-sale LaminateFloor Jurmala)  0)
        (= (price Copper Jurmala)    34.0)
        (= (on-sale Copper Jurmala)  10)
        (= (price Footballs Jurmala)    86.0)
        (= (on-sale Footballs Jurmala)  0)
        (= (price Kittens Jurmala)    45.2)
        (= (on-sale Kittens Jurmala)  27)
        (= (price Minerals Jurmala)    10.0)
        (= (on-sale Minerals Jurmala)  60)
        (= (price Gold Jurmala)    36.0)
        (= (on-sale Gold Jurmala)  9)
        (= (price Platinum Jurmala)    62.8)
        (= (on-sale Platinum Jurmala)  5)
        (= (price DVDs Jurmala)    15.2)
        (= (on-sale DVDs Jurmala)  1)
        (= (price TuringMachines Jurmala)    63.2)
        (= (on-sale TuringMachines Jurmala)  0)

        (= (price Food Valmiera)    2.8)
        (= (on-sale Food Valmiera)  18)
        (= (price ExpensiveRugs Valmiera)    5.6)
        (= (on-sale ExpensiveRugs Valmiera)  16)
        (= (price Coffee Valmiera)    18.8)
        (= (on-sale Coffee Valmiera)  20)
        (= (price Cattle Valmiera)    4.0)
        (= (on-sale Cattle Valmiera)  0)
        (= (price Water Valmiera)    21.2)
        (= (on-sale Water Valmiera)  25)
        (= (price Cars Valmiera)    97.6)
        (= (on-sale Cars Valmiera)  6)
        (= (price GummyBears Valmiera)    61.2)
        (= (on-sale GummyBears Valmiera)  26)
        (= (price Computers Valmiera)    95.2)
        (= (on-sale Computers Valmiera)  0)
        (= (price LaminateFloor Valmiera)    61.2)
        (= (on-sale LaminateFloor Valmiera)  4)
        (= (price Copper Valmiera)    33.6)
        (= (on-sale Copper Valmiera)  11)
        (= (price Footballs Valmiera)    80.8)
        (= (on-sale Footballs Valmiera)  0)
        (= (price Kittens Valmiera)    48.8)
        (= (on-sale Kittens Valmiera)  18)
        (= (price Minerals Valmiera)    10.3)
        (= (on-sale Minerals Valmiera)  59)
        (= (price Gold Valmiera)    36.3)
        (= (on-sale Gold Valmiera)  8)
        (= (price Platinum Valmiera)    63.6)
        (= (on-sale Platinum Valmiera)  3)
        (= (price DVDs Valmiera)    15.6)
        (= (on-sale DVDs Valmiera)  0)
        (= (price TuringMachines Valmiera)    57.2)
        (= (on-sale TuringMachines Valmiera)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Narva Oslo ) 4.9)
        (= (drive-cost Oslo Narva ) 4.9)
        (can-drive Narva Oslo)
        (can-drive Oslo Narva)
        (= (drive-cost Narva Jelgava ) 4.8)
        (= (drive-cost Jelgava Narva ) 4.8)
        (can-drive Narva Jelgava)
        (can-drive Jelgava Narva)
        (= (drive-cost Narva Jurmala ) 4.9)
        (= (drive-cost Jurmala Narva ) 4.9)
        (can-drive Narva Jurmala)
        (can-drive Jurmala Narva)
        (= (drive-cost Narva Valmiera ) 4.8)
        (= (drive-cost Valmiera Narva ) 4.8)
        (can-drive Narva Valmiera)
        (can-drive Valmiera Narva)
        (= (drive-cost Oslo Jelgava ) 5.7)
        (= (drive-cost Jelgava Oslo ) 5.7)
        (can-drive Oslo Jelgava)
        (can-drive Jelgava Oslo)
        (= (drive-cost Oslo Jurmala ) 6.3)
        (= (drive-cost Jurmala Oslo ) 6.3)
        (can-drive Oslo Jurmala)
        (can-drive Jurmala Oslo)
        (= (drive-cost Jelgava Jurmala ) 0.9)
        (= (drive-cost Jurmala Jelgava ) 0.9)
        (can-drive Jelgava Jurmala)
        (can-drive Jurmala Jelgava)
        (= (drive-cost Jurmala Valmiera ) 6.7)
        (= (drive-cost Valmiera Jurmala ) 6.7)
        (can-drive Jurmala Valmiera)
        (can-drive Valmiera Jurmala)
        (at camel0    Valmiera)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
