(define (problem marketcount5)
(:domain Trader)
(:objects
           Rakvere Panemune Kavarskas Dusetos   Seda  - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Rakvere)    5.2)
        (= (on-sale Food Rakvere)  12)
        (= (price ExpensiveRugs Rakvere)    6.8)
        (= (on-sale ExpensiveRugs Rakvere)  13)
        (= (price Coffee Rakvere)    22.3)
        (= (on-sale Coffee Rakvere)  11)
        (= (price Cattle Rakvere)    10.0)
        (= (on-sale Cattle Rakvere)  0)
        (= (price Water Rakvere)    27.2)
        (= (on-sale Water Rakvere)  10)
        (= (price Cars Rakvere)    88.0)
        (= (on-sale Cars Rakvere)  30)
        (= (price GummyBears Rakvere)    26.3)
        (= (on-sale GummyBears Rakvere)  0)
        (= (price Computers Rakvere)    78.3)
        (= (on-sale Computers Rakvere)  14)
        (= (price LaminateFloor Rakvere)    54.0)
        (= (on-sale LaminateFloor Rakvere)  22)
        (= (price Copper Rakvere)    32.3)
        (= (on-sale Copper Rakvere)  14)
        (= (price Footballs Rakvere)    65.2)
        (= (on-sale Footballs Rakvere)  0)
        (= (price Kittens Rakvere)    59.6)
        (= (on-sale Kittens Rakvere)  0)
        (= (price Minerals Rakvere)    11.6)
        (= (on-sale Minerals Rakvere)  56)
        (= (price Gold Rakvere)    37.6)
        (= (on-sale Gold Rakvere)  5)
        (= (price Platinum Rakvere)    66.0)
        (= (on-sale Platinum Rakvere)  61)
        (= (price DVDs Rakvere)    16.8)
        (= (on-sale DVDs Rakvere)  0)
        (= (price TuringMachines Rakvere)    39.2)
        (= (on-sale TuringMachines Rakvere)  0)

        (= (price Food Panemune)    2.0)
        (= (on-sale Food Panemune)  20)
        (= (price ExpensiveRugs Panemune)    5.2)
        (= (on-sale ExpensiveRugs Panemune)  17)
        (= (price Coffee Panemune)    17.6)
        (= (on-sale Coffee Panemune)  23)
        (= (price Cattle Panemune)    2.0)
        (= (on-sale Cattle Panemune)  5)
        (= (price Water Panemune)    19.2)
        (= (on-sale Water Panemune)  30)
        (= (price Cars Panemune)    100.8)
        (= (on-sale Cars Panemune)  0)
        (= (price GummyBears Panemune)    72.8)
        (= (on-sale GummyBears Panemune)  61)
        (= (price Computers Panemune)    100.8)
        (= (on-sale Computers Panemune)  0)
        (= (price LaminateFloor Panemune)    63.6)
        (= (on-sale LaminateFloor Panemune)  0)
        (= (price Copper Panemune)    34.0)
        (= (on-sale Copper Panemune)  10)
        (= (price Footballs Panemune)    86.0)
        (= (on-sale Footballs Panemune)  0)
        (= (price Kittens Panemune)    45.2)
        (= (on-sale Kittens Panemune)  27)
        (= (price Minerals Panemune)    10.0)
        (= (on-sale Minerals Panemune)  60)
        (= (price Gold Panemune)    36.0)
        (= (on-sale Gold Panemune)  9)
        (= (price Platinum Panemune)    62.8)
        (= (on-sale Platinum Panemune)  5)
        (= (price DVDs Panemune)    15.2)
        (= (on-sale DVDs Panemune)  1)
        (= (price TuringMachines Panemune)    63.2)
        (= (on-sale TuringMachines Panemune)  0)

        (= (price Food Kavarskas)    6.0)
        (= (on-sale Food Kavarskas)  10)
        (= (price ExpensiveRugs Kavarskas)    7.2)
        (= (on-sale ExpensiveRugs Kavarskas)  12)
        (= (price Coffee Kavarskas)    23.6)
        (= (on-sale Coffee Kavarskas)  8)
        (= (price Cattle Kavarskas)    12.0)
        (= (on-sale Cattle Kavarskas)  0)
        (= (price Water Kavarskas)    29.2)
        (= (on-sale Water Kavarskas)  5)
        (= (price Cars Kavarskas)    84.8)
        (= (on-sale Cars Kavarskas)  38)
        (= (price GummyBears Kavarskas)    14.8)
        (= (on-sale GummyBears Kavarskas)  0)
        (= (price Computers Kavarskas)    72.8)
        (= (on-sale Computers Kavarskas)  28)
        (= (price LaminateFloor Kavarskas)    51.6)
        (= (on-sale LaminateFloor Kavarskas)  28)
        (= (price Copper Kavarskas)    32.0)
        (= (on-sale Copper Kavarskas)  15)
        (= (price Footballs Kavarskas)    60.0)
        (= (on-sale Footballs Kavarskas)  3)
        (= (price Kittens Kavarskas)    63.2)
        (= (on-sale Kittens Kavarskas)  0)
        (= (price Minerals Kavarskas)    12.0)
        (= (on-sale Minerals Kavarskas)  55)
        (= (price Gold Kavarskas)    38.0)
        (= (on-sale Gold Kavarskas)  4)
        (= (price Platinum Kavarskas)    66.8)
        (= (on-sale Platinum Kavarskas)  59)
        (= (price DVDs Kavarskas)    17.2)
        (= (on-sale DVDs Kavarskas)  0)
        (= (price TuringMachines Kavarskas)    33.2)
        (= (on-sale TuringMachines Kavarskas)  0)

        (= (price Food Dusetos)    2.8)
        (= (on-sale Food Dusetos)  18)
        (= (price ExpensiveRugs Dusetos)    5.6)
        (= (on-sale ExpensiveRugs Dusetos)  16)
        (= (price Coffee Dusetos)    18.8)
        (= (on-sale Coffee Dusetos)  20)
        (= (price Cattle Dusetos)    4.0)
        (= (on-sale Cattle Dusetos)  0)
        (= (price Water Dusetos)    21.2)
        (= (on-sale Water Dusetos)  25)
        (= (price Cars Dusetos)    97.6)
        (= (on-sale Cars Dusetos)  6)
        (= (price GummyBears Dusetos)    61.2)
        (= (on-sale GummyBears Dusetos)  26)
        (= (price Computers Dusetos)    95.2)
        (= (on-sale Computers Dusetos)  0)
        (= (price LaminateFloor Dusetos)    61.2)
        (= (on-sale LaminateFloor Dusetos)  4)
        (= (price Copper Dusetos)    33.6)
        (= (on-sale Copper Dusetos)  11)
        (= (price Footballs Dusetos)    80.8)
        (= (on-sale Footballs Dusetos)  0)
        (= (price Kittens Dusetos)    48.8)
        (= (on-sale Kittens Dusetos)  18)
        (= (price Minerals Dusetos)    10.3)
        (= (on-sale Minerals Dusetos)  59)
        (= (price Gold Dusetos)    36.3)
        (= (on-sale Gold Dusetos)  8)
        (= (price Platinum Dusetos)    63.6)
        (= (on-sale Platinum Dusetos)  3)
        (= (price DVDs Dusetos)    15.6)
        (= (on-sale DVDs Dusetos)  0)
        (= (price TuringMachines Dusetos)    57.2)
        (= (on-sale TuringMachines Dusetos)  0)

        (= (price Food Seda)    5.2)
        (= (on-sale Food Seda)  12)
        (= (price ExpensiveRugs Seda)    6.8)
        (= (on-sale ExpensiveRugs Seda)  13)
        (= (price Coffee Seda)    22.3)
        (= (on-sale Coffee Seda)  11)
        (= (price Cattle Seda)    10.0)
        (= (on-sale Cattle Seda)  0)
        (= (price Water Seda)    27.2)
        (= (on-sale Water Seda)  10)
        (= (price Cars Seda)    88.0)
        (= (on-sale Cars Seda)  30)
        (= (price GummyBears Seda)    26.3)
        (= (on-sale GummyBears Seda)  0)
        (= (price Computers Seda)    78.3)
        (= (on-sale Computers Seda)  14)
        (= (price LaminateFloor Seda)    54.0)
        (= (on-sale LaminateFloor Seda)  22)
        (= (price Copper Seda)    32.3)
        (= (on-sale Copper Seda)  14)
        (= (price Footballs Seda)    65.2)
        (= (on-sale Footballs Seda)  0)
        (= (price Kittens Seda)    59.6)
        (= (on-sale Kittens Seda)  0)
        (= (price Minerals Seda)    11.6)
        (= (on-sale Minerals Seda)  56)
        (= (price Gold Seda)    37.6)
        (= (on-sale Gold Seda)  5)
        (= (price Platinum Seda)    66.0)
        (= (on-sale Platinum Seda)  61)
        (= (price DVDs Seda)    16.8)
        (= (on-sale DVDs Seda)  0)
        (= (price TuringMachines Seda)    39.2)
        (= (on-sale TuringMachines Seda)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Rakvere Panemune ) 4.7)
        (= (drive-cost Panemune Rakvere ) 4.7)
        (can-drive Rakvere Panemune)
        (can-drive Panemune Rakvere)
        (= (drive-cost Rakvere Kavarskas ) 6.5)
        (= (drive-cost Kavarskas Rakvere ) 6.5)
        (can-drive Rakvere Kavarskas)
        (can-drive Kavarskas Rakvere)
        (= (drive-cost Rakvere Dusetos ) 5.0)
        (= (drive-cost Dusetos Rakvere ) 5.0)
        (can-drive Rakvere Dusetos)
        (can-drive Dusetos Rakvere)
        (= (drive-cost Rakvere Seda ) 3.0)
        (= (drive-cost Seda Rakvere ) 3.0)
        (can-drive Rakvere Seda)
        (can-drive Seda Rakvere)
        (= (drive-cost Kavarskas Dusetos ) 5.7)
        (= (drive-cost Dusetos Kavarskas ) 5.7)
        (can-drive Kavarskas Dusetos)
        (can-drive Dusetos Kavarskas)
        (= (drive-cost Kavarskas Seda ) 3.5)
        (= (drive-cost Seda Kavarskas ) 3.5)
        (can-drive Kavarskas Seda)
        (can-drive Seda Kavarskas)
        (= (drive-cost Dusetos Seda ) 4.5)
        (= (drive-cost Seda Dusetos ) 4.5)
        (can-drive Dusetos Seda)
        (can-drive Seda Dusetos)
        (at camel0    Seda)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
