(define (problem marketcount3)
(:domain Trader)
(:objects
            Vilkija Neringa Berlin - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Vilkija)    2.8)
        (= (on-sale Food Vilkija)  18)
        (= (price ExpensiveRugs Vilkija)    5.6)
        (= (on-sale ExpensiveRugs Vilkija)  16)
        (= (price Coffee Vilkija)    18.8)
        (= (on-sale Coffee Vilkija)  20)
        (= (price Cattle Vilkija)    4.0)
        (= (on-sale Cattle Vilkija)  0)
        (= (price Water Vilkija)    21.2)
        (= (on-sale Water Vilkija)  25)
        (= (price Cars Vilkija)    97.6)
        (= (on-sale Cars Vilkija)  6)
        (= (price GummyBears Vilkija)    61.2)
        (= (on-sale GummyBears Vilkija)  26)
        (= (price Computers Vilkija)    95.2)
        (= (on-sale Computers Vilkija)  0)
        (= (price LaminateFloor Vilkija)    61.2)
        (= (on-sale LaminateFloor Vilkija)  4)
        (= (price Copper Vilkija)    33.6)
        (= (on-sale Copper Vilkija)  11)
        (= (price Footballs Vilkija)    80.8)
        (= (on-sale Footballs Vilkija)  0)
        (= (price Kittens Vilkija)    48.8)
        (= (on-sale Kittens Vilkija)  18)
        (= (price Minerals Vilkija)    10.3)
        (= (on-sale Minerals Vilkija)  59)
        (= (price Gold Vilkija)    36.3)
        (= (on-sale Gold Vilkija)  8)
        (= (price Platinum Vilkija)    63.6)
        (= (on-sale Platinum Vilkija)  3)
        (= (price DVDs Vilkija)    15.6)
        (= (on-sale DVDs Vilkija)  0)
        (= (price TuringMachines Vilkija)    57.2)
        (= (on-sale TuringMachines Vilkija)  0)

        (= (price Food Neringa)    7.6)
        (= (on-sale Food Neringa)  6)
        (= (price ExpensiveRugs Neringa)    8.0)
        (= (on-sale ExpensiveRugs Neringa)  10)
        (= (price Coffee Neringa)    26.0)
        (= (on-sale Coffee Neringa)  2)
        (= (price Cattle Neringa)    16.0)
        (= (on-sale Cattle Neringa)  0)
        (= (price Water Neringa)    33.2)
        (= (on-sale Water Neringa)  0)
        (= (price Cars Neringa)    78.3)
        (= (on-sale Cars Neringa)  54)
        (= (price GummyBears Neringa)    94.0)
        (= (on-sale GummyBears Neringa)  8)
        (= (price Computers Neringa)    61.6)
        (= (on-sale Computers Neringa)  56)
        (= (price LaminateFloor Neringa)    46.8)
        (= (on-sale LaminateFloor Neringa)  40)
        (= (price Copper Neringa)    31.2)
        (= (on-sale Copper Neringa)  17)
        (= (price Footballs Neringa)    49.6)
        (= (on-sale Footballs Neringa)  29)
        (= (price Kittens Neringa)    70.3)
        (= (on-sale Kittens Neringa)  0)
        (= (price Minerals Neringa)    12.8)
        (= (on-sale Minerals Neringa)  53)
        (= (price Gold Neringa)    38.8)
        (= (on-sale Gold Neringa)  2)
        (= (price Platinum Neringa)    68.3)
        (= (on-sale Platinum Neringa)  55)
        (= (price DVDs Neringa)    18.0)
        (= (on-sale DVDs Neringa)  0)
        (= (price TuringMachines Neringa)    21.2)
        (= (on-sale TuringMachines Neringa)  0)

        (= (price Food Berlin)    3.6)
        (= (on-sale Food Berlin)  16)
        (= (price ExpensiveRugs Berlin)    6.0)
        (= (on-sale ExpensiveRugs Berlin)  15)
        (= (price Coffee Berlin)    20.0)
        (= (on-sale Coffee Berlin)  17)
        (= (price Cattle Berlin)    6.0)
        (= (on-sale Cattle Berlin)  0)
        (= (price Water Berlin)    23.2)
        (= (on-sale Water Berlin)  20)
        (= (price Cars Berlin)    94.3)
        (= (on-sale Cars Berlin)  14)
        (= (price GummyBears Berlin)    49.6)
        (= (on-sale GummyBears Berlin)  55)
        (= (price Computers Berlin)    89.6)
        (= (on-sale Computers Berlin)  0)
        (= (price LaminateFloor Berlin)    58.8)
        (= (on-sale LaminateFloor Berlin)  10)
        (= (price Copper Berlin)    33.2)
        (= (on-sale Copper Berlin)  12)
        (= (price Footballs Berlin)    75.6)
        (= (on-sale Footballs Berlin)  0)
        (= (price Kittens Berlin)    52.3)
        (= (on-sale Kittens Berlin)  9)
        (= (price Minerals Berlin)    10.8)
        (= (on-sale Minerals Berlin)  58)
        (= (price Gold Berlin)    36.8)
        (= (on-sale Gold Berlin)  7)
        (= (price Platinum Berlin)    64.3)
        (= (on-sale Platinum Berlin)  1)
        (= (price DVDs Berlin)    16.0)
        (= (on-sale DVDs Berlin)  0)
        (= (price TuringMachines Berlin)    51.2)
        (= (on-sale TuringMachines Berlin)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Vilkija Neringa ) 5.3)
        (= (drive-cost Neringa Vilkija ) 5.3)
        (can-drive Vilkija Neringa)
        (can-drive Neringa Vilkija)
        (= (drive-cost Vilkija Berlin ) 5.8)
        (= (drive-cost Berlin Vilkija ) 5.8)
        (can-drive Vilkija Berlin)
        (can-drive Berlin Vilkija)
        (at camel0       Berlin)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
