(define (problem marketcount3)
(:domain Trader)
(:objects
            Simnas KudirkosNaumiestis Gelgaudiskis - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Simnas)    7.6)
        (= (on-sale Food Simnas)  6)
        (= (price ExpensiveRugs Simnas)    8.0)
        (= (on-sale ExpensiveRugs Simnas)  10)
        (= (price Coffee Simnas)    26.0)
        (= (on-sale Coffee Simnas)  2)
        (= (price Cattle Simnas)    16.0)
        (= (on-sale Cattle Simnas)  0)
        (= (price Water Simnas)    33.2)
        (= (on-sale Water Simnas)  0)
        (= (price Cars Simnas)    78.3)
        (= (on-sale Cars Simnas)  54)
        (= (price GummyBears Simnas)    94.0)
        (= (on-sale GummyBears Simnas)  8)
        (= (price Computers Simnas)    61.6)
        (= (on-sale Computers Simnas)  56)
        (= (price LaminateFloor Simnas)    46.8)
        (= (on-sale LaminateFloor Simnas)  40)
        (= (price Copper Simnas)    31.2)
        (= (on-sale Copper Simnas)  17)
        (= (price Footballs Simnas)    49.6)
        (= (on-sale Footballs Simnas)  29)
        (= (price Kittens Simnas)    70.3)
        (= (on-sale Kittens Simnas)  0)
        (= (price Minerals Simnas)    12.8)
        (= (on-sale Minerals Simnas)  53)
        (= (price Gold Simnas)    38.8)
        (= (on-sale Gold Simnas)  2)
        (= (price Platinum Simnas)    68.3)
        (= (on-sale Platinum Simnas)  55)
        (= (price DVDs Simnas)    18.0)
        (= (on-sale DVDs Simnas)  0)
        (= (price TuringMachines Simnas)    21.2)
        (= (on-sale TuringMachines Simnas)  0)

        (= (price Food KudirkosNaumiestis)    5.2)
        (= (on-sale Food KudirkosNaumiestis)  12)
        (= (price ExpensiveRugs KudirkosNaumiestis)    6.8)
        (= (on-sale ExpensiveRugs KudirkosNaumiestis)  13)
        (= (price Coffee KudirkosNaumiestis)    22.3)
        (= (on-sale Coffee KudirkosNaumiestis)  11)
        (= (price Cattle KudirkosNaumiestis)    10.0)
        (= (on-sale Cattle KudirkosNaumiestis)  0)
        (= (price Water KudirkosNaumiestis)    27.2)
        (= (on-sale Water KudirkosNaumiestis)  10)
        (= (price Cars KudirkosNaumiestis)    88.0)
        (= (on-sale Cars KudirkosNaumiestis)  30)
        (= (price GummyBears KudirkosNaumiestis)    26.3)
        (= (on-sale GummyBears KudirkosNaumiestis)  0)
        (= (price Computers KudirkosNaumiestis)    78.3)
        (= (on-sale Computers KudirkosNaumiestis)  14)
        (= (price LaminateFloor KudirkosNaumiestis)    54.0)
        (= (on-sale LaminateFloor KudirkosNaumiestis)  22)
        (= (price Copper KudirkosNaumiestis)    32.3)
        (= (on-sale Copper KudirkosNaumiestis)  14)
        (= (price Footballs KudirkosNaumiestis)    65.2)
        (= (on-sale Footballs KudirkosNaumiestis)  0)
        (= (price Kittens KudirkosNaumiestis)    59.6)
        (= (on-sale Kittens KudirkosNaumiestis)  0)
        (= (price Minerals KudirkosNaumiestis)    11.6)
        (= (on-sale Minerals KudirkosNaumiestis)  56)
        (= (price Gold KudirkosNaumiestis)    37.6)
        (= (on-sale Gold KudirkosNaumiestis)  5)
        (= (price Platinum KudirkosNaumiestis)    66.0)
        (= (on-sale Platinum KudirkosNaumiestis)  61)
        (= (price DVDs KudirkosNaumiestis)    16.8)
        (= (on-sale DVDs KudirkosNaumiestis)  0)
        (= (price TuringMachines KudirkosNaumiestis)    39.2)
        (= (on-sale TuringMachines KudirkosNaumiestis)  0)

        (= (price Food Gelgaudiskis)    3.6)
        (= (on-sale Food Gelgaudiskis)  16)
        (= (price ExpensiveRugs Gelgaudiskis)    6.0)
        (= (on-sale ExpensiveRugs Gelgaudiskis)  15)
        (= (price Coffee Gelgaudiskis)    20.0)
        (= (on-sale Coffee Gelgaudiskis)  17)
        (= (price Cattle Gelgaudiskis)    6.0)
        (= (on-sale Cattle Gelgaudiskis)  0)
        (= (price Water Gelgaudiskis)    23.2)
        (= (on-sale Water Gelgaudiskis)  20)
        (= (price Cars Gelgaudiskis)    94.3)
        (= (on-sale Cars Gelgaudiskis)  14)
        (= (price GummyBears Gelgaudiskis)    49.6)
        (= (on-sale GummyBears Gelgaudiskis)  55)
        (= (price Computers Gelgaudiskis)    89.6)
        (= (on-sale Computers Gelgaudiskis)  0)
        (= (price LaminateFloor Gelgaudiskis)    58.8)
        (= (on-sale LaminateFloor Gelgaudiskis)  10)
        (= (price Copper Gelgaudiskis)    33.2)
        (= (on-sale Copper Gelgaudiskis)  12)
        (= (price Footballs Gelgaudiskis)    75.6)
        (= (on-sale Footballs Gelgaudiskis)  0)
        (= (price Kittens Gelgaudiskis)    52.3)
        (= (on-sale Kittens Gelgaudiskis)  9)
        (= (price Minerals Gelgaudiskis)    10.8)
        (= (on-sale Minerals Gelgaudiskis)  58)
        (= (price Gold Gelgaudiskis)    36.8)
        (= (on-sale Gold Gelgaudiskis)  7)
        (= (price Platinum Gelgaudiskis)    64.3)
        (= (on-sale Platinum Gelgaudiskis)  1)
        (= (price DVDs Gelgaudiskis)    16.0)
        (= (on-sale DVDs Gelgaudiskis)  0)
        (= (price TuringMachines Gelgaudiskis)    51.2)
        (= (on-sale TuringMachines Gelgaudiskis)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Simnas KudirkosNaumiestis ) 3.0)
        (= (drive-cost KudirkosNaumiestis Simnas ) 3.0)
        (can-drive Simnas KudirkosNaumiestis)
        (can-drive KudirkosNaumiestis Simnas)
        (= (drive-cost Simnas Gelgaudiskis ) 3.9)
        (= (drive-cost Gelgaudiskis Simnas ) 3.9)
        (can-drive Simnas Gelgaudiskis)
        (can-drive Gelgaudiskis Simnas)
        (= (drive-cost KudirkosNaumiestis Gelgaudiskis ) 6.6)
        (= (drive-cost Gelgaudiskis KudirkosNaumiestis ) 6.6)
        (can-drive KudirkosNaumiestis Gelgaudiskis)
        (can-drive Gelgaudiskis KudirkosNaumiestis)
        (at camel0    Gelgaudiskis)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
