(define (problem marketcount3)
(:domain Trader)
(:objects
               Mandres Daugai Jieznas  - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Mandres)    6.0)
        (= (on-sale Food Mandres)  10)
        (= (price ExpensiveRugs Mandres)    7.2)
        (= (on-sale ExpensiveRugs Mandres)  12)
        (= (price Coffee Mandres)    23.6)
        (= (on-sale Coffee Mandres)  8)
        (= (price Cattle Mandres)    12.0)
        (= (on-sale Cattle Mandres)  0)
        (= (price Water Mandres)    29.2)
        (= (on-sale Water Mandres)  5)
        (= (price Cars Mandres)    84.8)
        (= (on-sale Cars Mandres)  38)
        (= (price GummyBears Mandres)    14.8)
        (= (on-sale GummyBears Mandres)  0)
        (= (price Computers Mandres)    72.8)
        (= (on-sale Computers Mandres)  28)
        (= (price LaminateFloor Mandres)    51.6)
        (= (on-sale LaminateFloor Mandres)  28)
        (= (price Copper Mandres)    32.0)
        (= (on-sale Copper Mandres)  15)
        (= (price Footballs Mandres)    60.0)
        (= (on-sale Footballs Mandres)  3)
        (= (price Kittens   Mandres)    63.2)
        (= (on-sale Kittens   Mandres)  0)
        (= (price Minerals Mandres)    12.0)
        (= (on-sale Minerals Mandres)  55)
        (= (price Gold   Mandres)    38.0)
        (= (on-sale Gold   Mandres)  4)
        (= (price Platinum Mandres)    66.8)
        (= (on-sale Platinum Mandres)  59)
        (= (price DVDs Mandres)    17.2)
        (= (on-sale DVDs Mandres)  0)
        (= (price TuringMachines Mandres)    33.2)
        (= (on-sale TuringMachines Mandres)  0)

        (= (price Food Daugai)    4.3)
        (= (on-sale Food Daugai)  14)
        (= (price ExpensiveRugs Daugai)    6.3)
        (= (on-sale ExpensiveRugs Daugai)  14)
        (= (price Coffee Daugai)    21.2)
        (= (on-sale Coffee Daugai)  14)
        (= (price Cattle Daugai)    8.0)
        (= (on-sale Cattle Daugai)  0)
        (= (price Water Daugai)    25.2)
        (= (on-sale Water Daugai)  15)
        (= (price Cars Daugai)    91.2)
        (= (on-sale Cars Daugai)  22)
        (= (price GummyBears Daugai)    38.0)
        (= (on-sale GummyBears Daugai)  0)
        (= (price Computers Daugai)    84.0)
        (= (on-sale Computers Daugai)  0)
        (= (price LaminateFloor Daugai)    56.3)
        (= (on-sale LaminateFloor Daugai)  16)
        (= (price Copper Daugai)    32.8)
        (= (on-sale Copper Daugai)  13)
        (= (price Footballs Daugai)    70.3)
        (= (on-sale Footballs Daugai)  0)
        (= (price Kittens Daugai)    56.0)
        (= (on-sale Kittens Daugai)  0)
        (= (price Minerals Daugai)    11.2)
        (= (on-sale Minerals Daugai)  57)
        (= (price Gold Daugai)    37.2)
        (= (on-sale Gold Daugai)  6)
        (= (price Platinum Daugai)    65.2)
        (= (on-sale Platinum Daugai)  63)
        (= (price DVDs Daugai)    16.3)
        (= (on-sale DVDs Daugai)  0)
        (= (price TuringMachines Daugai)    45.2)
        (= (on-sale TuringMachines Daugai)  0)

        (= (price Food Jieznas)    2.0)
        (= (on-sale Food Jieznas)  20)
        (= (price ExpensiveRugs Jieznas)    5.2)
        (= (on-sale ExpensiveRugs Jieznas)  17)
        (= (price Coffee Jieznas)    17.6)
        (= (on-sale Coffee Jieznas)  23)
        (= (price Cattle Jieznas)    2.0)
        (= (on-sale Cattle Jieznas)  5)
        (= (price Water Jieznas)    19.2)
        (= (on-sale Water Jieznas)  30)
        (= (price Cars Jieznas)    100.8)
        (= (on-sale Cars Jieznas)  0)
        (= (price GummyBears Jieznas)    72.8)
        (= (on-sale GummyBears Jieznas)  61)
        (= (price Computers Jieznas)    100.8)
        (= (on-sale Computers Jieznas)  0)
        (= (price LaminateFloor Jieznas)    63.6)
        (= (on-sale LaminateFloor Jieznas)  0)
        (= (price Copper Jieznas)    34.0)
        (= (on-sale Copper Jieznas)  10)
        (= (price Footballs Jieznas)    86.0)
        (= (on-sale Footballs Jieznas)  0)
        (= (price Kittens Jieznas)    45.2)
        (= (on-sale Kittens Jieznas)  27)
        (= (price Minerals Jieznas)    10.0)
        (= (on-sale Minerals Jieznas)  60)
        (= (price Gold Jieznas)    36.0)
        (= (on-sale Gold Jieznas)  9)
        (= (price Platinum Jieznas)    62.8)
        (= (on-sale Platinum Jieznas)  5)
        (= (price DVDs Jieznas)    15.2)
        (= (on-sale DVDs Jieznas)  1)
        (= (price TuringMachines Jieznas)    63.2)
        (= (on-sale TuringMachines Jieznas)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Mandres Daugai ) 5.7)
        (= (drive-cost Daugai Mandres ) 5.7)
        (can-drive Mandres Daugai)
        (can-drive Daugai Mandres)
        (= (drive-cost Mandres Jieznas ) 1.6)
        (= (drive-cost Jieznas Mandres ) 1.6)
        (can-drive Mandres Jieznas)
        (can-drive Jieznas Mandres)
        (= (drive-cost Daugai Jieznas ) 6.3)
        (= (drive-cost Jieznas Daugai ) 6.3)
        (can-drive Daugai Jieznas)
        (can-drive Jieznas Daugai)
        (at camel0    Jieznas)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
