(define (problem marketcount4)
(:domain Trader)
(:objects
          Mariehamn Tallinn Dublin Douglas - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Mariehamn)    6.8)
        (= (on-sale Food Mariehamn)  8)
        (= (price ExpensiveRugs Mariehamn)    7.6)
        (= (on-sale ExpensiveRugs Mariehamn)  11)
        (= (price Coffee Mariehamn)    24.8)
        (= (on-sale Coffee Mariehamn)  5)
        (= (price Cattle Mariehamn)    14.0)
        (= (on-sale Cattle Mariehamn)  0)
        (= (price Water Mariehamn)    31.2)
        (= (on-sale Water Mariehamn)  0)
        (= (price Cars Mariehamn)    81.6)
        (= (on-sale Cars Mariehamn)  46)
        (= (price GummyBears Mariehamn)    3.2)
        (= (on-sale GummyBears Mariehamn)  0)
        (= (price Computers Mariehamn)    67.2)
        (= (on-sale Computers Mariehamn)  42)
        (= (price LaminateFloor Mariehamn)    49.2)
        (= (on-sale LaminateFloor Mariehamn)  34)
        (= (price Copper Mariehamn)    31.6)
        (= (on-sale Copper Mariehamn)  16)
        (= (price Footballs Mariehamn)    54.8)
        (= (on-sale Footballs Mariehamn)  16)
        (= (price Kittens Mariehamn)    66.8)
        (= (on-sale Kittens Mariehamn)  0)
        (= (price Minerals Mariehamn)    12.3)
        (= (on-sale Minerals Mariehamn)  54)
        (= (price Gold Mariehamn)    38.3)
        (= (on-sale Gold Mariehamn)  3)
        (= (price Platinum Mariehamn)    67.6)
        (= (on-sale Platinum Mariehamn)  57)
        (= (price DVDs Mariehamn)    17.6)
        (= (on-sale DVDs Mariehamn)  0)
        (= (price TuringMachines Mariehamn)    27.2)
        (= (on-sale TuringMachines Mariehamn)  0)

        (= (price Food Tallinn)    5.2)
        (= (on-sale Food Tallinn)  12)
        (= (price ExpensiveRugs Tallinn)    6.8)
        (= (on-sale ExpensiveRugs Tallinn)  13)
        (= (price Coffee Tallinn)    22.3)
        (= (on-sale Coffee Tallinn)  11)
        (= (price Cattle Tallinn)    10.0)
        (= (on-sale Cattle Tallinn)  0)
        (= (price Water Tallinn)    27.2)
        (= (on-sale Water Tallinn)  10)
        (= (price Cars Tallinn)    88.0)
        (= (on-sale Cars Tallinn)  30)
        (= (price GummyBears Tallinn)    26.3)
        (= (on-sale GummyBears Tallinn)  0)
        (= (price Computers Tallinn)    78.3)
        (= (on-sale Computers Tallinn)  14)
        (= (price LaminateFloor Tallinn)    54.0)
        (= (on-sale LaminateFloor Tallinn)  22)
        (= (price Copper Tallinn)    32.3)
        (= (on-sale Copper Tallinn)  14)
        (= (price Footballs Tallinn)    65.2)
        (= (on-sale Footballs Tallinn)  0)
        (= (price Kittens Tallinn)    59.6)
        (= (on-sale Kittens Tallinn)  0)
        (= (price Minerals Tallinn)    11.6)
        (= (on-sale Minerals Tallinn)  56)
        (= (price Gold Tallinn)    37.6)
        (= (on-sale Gold Tallinn)  5)
        (= (price Platinum Tallinn)    66.0)
        (= (on-sale Platinum Tallinn)  61)
        (= (price DVDs Tallinn)    16.8)
        (= (on-sale DVDs Tallinn)  0)
        (= (price TuringMachines Tallinn)    39.2)
        (= (on-sale TuringMachines Tallinn)  0)

        (= (price Food Dublin)    6.8)
        (= (on-sale Food Dublin)  8)
        (= (price ExpensiveRugs Dublin)    7.6)
        (= (on-sale ExpensiveRugs Dublin)  11)
        (= (price Coffee Dublin)    24.8)
        (= (on-sale Coffee Dublin)  5)
        (= (price Cattle Dublin)    14.0)
        (= (on-sale Cattle Dublin)  0)
        (= (price Water Dublin)    31.2)
        (= (on-sale Water Dublin)  0)
        (= (price Cars Dublin)    81.6)
        (= (on-sale Cars Dublin)  46)
        (= (price GummyBears Dublin)    3.2)
        (= (on-sale GummyBears Dublin)  0)
        (= (price Computers Dublin)    67.2)
        (= (on-sale Computers Dublin)  42)
        (= (price LaminateFloor Dublin)    49.2)
        (= (on-sale LaminateFloor Dublin)  34)
        (= (price Copper Dublin)    31.6)
        (= (on-sale Copper Dublin)  16)
        (= (price Footballs Dublin)    54.8)
        (= (on-sale Footballs Dublin)  16)
        (= (price Kittens Dublin)    66.8)
        (= (on-sale Kittens Dublin)  0)
        (= (price Minerals Dublin)    12.3)
        (= (on-sale Minerals Dublin)  54)
        (= (price Gold Dublin)    38.3)
        (= (on-sale Gold Dublin)  3)
        (= (price Platinum Dublin)    67.6)
        (= (on-sale Platinum Dublin)  57)
        (= (price DVDs Dublin)    17.6)
        (= (on-sale DVDs Dublin)  0)
        (= (price TuringMachines Dublin)    27.2)
        (= (on-sale TuringMachines Dublin)  0)

        (= (price Food Douglas)    2.0)
        (= (on-sale Food Douglas)  20)
        (= (price ExpensiveRugs Douglas)    5.2)
        (= (on-sale ExpensiveRugs Douglas)  17)
        (= (price Coffee Douglas)    17.6)
        (= (on-sale Coffee Douglas)  23)
        (= (price Cattle Douglas)    2.0)
        (= (on-sale Cattle Douglas)  5)
        (= (price Water Douglas)    19.2)
        (= (on-sale Water Douglas)  30)
        (= (price Cars Douglas)    100.8)
        (= (on-sale Cars Douglas)  0)
        (= (price GummyBears Douglas)    72.8)
        (= (on-sale GummyBears Douglas)  61)
        (= (price Computers Douglas)    100.8)
        (= (on-sale Computers Douglas)  0)
        (= (price LaminateFloor Douglas)    63.6)
        (= (on-sale LaminateFloor Douglas)  0)
        (= (price Copper Douglas)    34.0)
        (= (on-sale Copper Douglas)  10)
        (= (price Footballs Douglas)    86.0)
        (= (on-sale Footballs Douglas)  0)
        (= (price Kittens Douglas)    45.2)
        (= (on-sale Kittens Douglas)  27)
        (= (price Minerals Douglas)    10.0)
        (= (on-sale Minerals Douglas)  60)
        (= (price Gold Douglas)    36.0)
        (= (on-sale Gold Douglas)  9)
        (= (price Platinum Douglas)    62.8)
        (= (on-sale Platinum Douglas)  5)
        (= (price DVDs Douglas)    15.2)
        (= (on-sale DVDs Douglas)  1)
        (= (price TuringMachines Douglas)    63.2)
        (= (on-sale TuringMachines Douglas)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Mariehamn Tallinn ) 6.8)
        (= (drive-cost Tallinn Mariehamn ) 6.8)
        (can-drive Mariehamn Tallinn)
        (can-drive Tallinn Mariehamn)
        (= (drive-cost Mariehamn Dublin ) 2.6)
        (= (drive-cost Dublin Mariehamn ) 2.6)
        (can-drive Mariehamn Dublin)
        (can-drive Dublin Mariehamn)
        (= (drive-cost Mariehamn Douglas ) 3.6)
        (= (drive-cost Douglas Mariehamn ) 3.6)
        (can-drive Mariehamn Douglas)
        (can-drive Douglas Mariehamn)
        (= (drive-cost Tallinn Douglas ) 4.3)
        (= (drive-cost Douglas Tallinn ) 4.3)
        (can-drive Tallinn Douglas)
        (can-drive Douglas Tallinn)
        (= (drive-cost Dublin Douglas ) 5.7)
        (= (drive-cost Douglas Dublin ) 5.7)
        (can-drive Dublin Douglas)
        (can-drive Douglas Dublin)
        (at camel0      Douglas)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
