(define (problem marketcount4)
(:domain Trader)
(:objects
            Vienna Bonn Copenhagen  Stockholm  - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Vienna)    5.2)
        (= (on-sale Food Vienna)  12)
        (= (price ExpensiveRugs Vienna)    6.8)
        (= (on-sale ExpensiveRugs Vienna)  13)
        (= (price Coffee Vienna)    22.3)
        (= (on-sale Coffee Vienna)  11)
        (= (price Cattle Vienna)    10.0)
        (= (on-sale Cattle Vienna)  0)
        (= (price Water Vienna)    27.2)
        (= (on-sale Water Vienna)  10)
        (= (price Cars Vienna)    88.0)
        (= (on-sale Cars Vienna)  30)
        (= (price GummyBears Vienna)    26.3)
        (= (on-sale GummyBears Vienna)  0)
        (= (price Computers Vienna)    78.3)
        (= (on-sale Computers Vienna)  14)
        (= (price LaminateFloor Vienna)    54.0)
        (= (on-sale LaminateFloor Vienna)  22)
        (= (price Copper Vienna)    32.3)
        (= (on-sale Copper Vienna)  14)
        (= (price Footballs Vienna)    65.2)
        (= (on-sale Footballs Vienna)  0)
        (= (price Kittens Vienna)    59.6)
        (= (on-sale Kittens Vienna)  0)
        (= (price Minerals Vienna)    11.6)
        (= (on-sale Minerals Vienna)  56)
        (= (price Gold Vienna)    37.6)
        (= (on-sale Gold Vienna)  5)
        (= (price Platinum Vienna)    66.0)
        (= (on-sale Platinum Vienna)  61)
        (= (price DVDs Vienna)    16.8)
        (= (on-sale DVDs Vienna)  0)
        (= (price TuringMachines Vienna)    39.2)
        (= (on-sale TuringMachines Vienna)  0)

        (= (price Food Bonn)    2.0)
        (= (on-sale Food Bonn)  20)
        (= (price ExpensiveRugs Bonn)    5.2)
        (= (on-sale ExpensiveRugs Bonn)  17)
        (= (price Coffee Bonn)    17.6)
        (= (on-sale Coffee Bonn)  23)
        (= (price Cattle Bonn)    2.0)
        (= (on-sale Cattle Bonn)  5)
        (= (price Water Bonn)    19.2)
        (= (on-sale Water Bonn)  30)
        (= (price Cars Bonn)    100.8)
        (= (on-sale Cars Bonn)  0)
        (= (price GummyBears Bonn)    72.8)
        (= (on-sale GummyBears Bonn)  61)
        (= (price Computers Bonn)    100.8)
        (= (on-sale Computers Bonn)  0)
        (= (price LaminateFloor Bonn)    63.6)
        (= (on-sale LaminateFloor Bonn)  0)
        (= (price Copper Bonn)    34.0)
        (= (on-sale Copper Bonn)  10)
        (= (price Footballs Bonn)    86.0)
        (= (on-sale Footballs Bonn)  0)
        (= (price Kittens Bonn)    45.2)
        (= (on-sale Kittens Bonn)  27)
        (= (price Minerals Bonn)    10.0)
        (= (on-sale Minerals Bonn)  60)
        (= (price Gold Bonn)    36.0)
        (= (on-sale Gold Bonn)  9)
        (= (price Platinum Bonn)    62.8)
        (= (on-sale Platinum Bonn)  5)
        (= (price DVDs Bonn)    15.2)
        (= (on-sale DVDs Bonn)  1)
        (= (price TuringMachines Bonn)    63.2)
        (= (on-sale TuringMachines Bonn)  0)

        (= (price Food Copenhagen)    2.0)
        (= (on-sale Food Copenhagen)  20)
        (= (price ExpensiveRugs Copenhagen)    5.2)
        (= (on-sale ExpensiveRugs Copenhagen)  17)
        (= (price Coffee Copenhagen)    17.6)
        (= (on-sale Coffee Copenhagen)  23)
        (= (price Cattle Copenhagen)    2.0)
        (= (on-sale Cattle Copenhagen)  5)
        (= (price Water Copenhagen)    19.2)
        (= (on-sale Water Copenhagen)  30)
        (= (price Cars Copenhagen)    100.8)
        (= (on-sale Cars Copenhagen)  0)
        (= (price GummyBears Copenhagen)    72.8)
        (= (on-sale GummyBears Copenhagen)  61)
        (= (price Computers Copenhagen)    100.8)
        (= (on-sale Computers Copenhagen)  0)
        (= (price LaminateFloor Copenhagen)    63.6)
        (= (on-sale LaminateFloor Copenhagen)  0)
        (= (price Copper Copenhagen)    34.0)
        (= (on-sale Copper Copenhagen)  10)
        (= (price Footballs Copenhagen)    86.0)
        (= (on-sale Footballs Copenhagen)  0)
        (= (price Kittens Copenhagen)    45.2)
        (= (on-sale Kittens Copenhagen)  27)
        (= (price Minerals Copenhagen)    10.0)
        (= (on-sale Minerals Copenhagen)  60)
        (= (price Gold Copenhagen)    36.0)
        (= (on-sale Gold Copenhagen)  9)
        (= (price Platinum Copenhagen)    62.8)
        (= (on-sale Platinum Copenhagen)  5)
        (= (price DVDs Copenhagen)    15.2)
        (= (on-sale DVDs Copenhagen)  1)
        (= (price TuringMachines Copenhagen)    63.2)
        (= (on-sale TuringMachines Copenhagen)  0)

        (= (price Food Stockholm)    2.0)
        (= (on-sale Food Stockholm)  20)
        (= (price ExpensiveRugs Stockholm)    5.2)
        (= (on-sale ExpensiveRugs Stockholm)  17)
        (= (price Coffee Stockholm)    17.6)
        (= (on-sale Coffee Stockholm)  23)
        (= (price Cattle Stockholm)    2.0)
        (= (on-sale Cattle Stockholm)  5)
        (= (price Water Stockholm)    19.2)
        (= (on-sale Water Stockholm)  30)
        (= (price Cars Stockholm)    100.8)
        (= (on-sale Cars Stockholm)  0)
        (= (price GummyBears Stockholm)    72.8)
        (= (on-sale GummyBears Stockholm)  61)
        (= (price Computers Stockholm)    100.8)
        (= (on-sale Computers Stockholm)  0)
        (= (price LaminateFloor Stockholm)    63.6)
        (= (on-sale LaminateFloor Stockholm)  0)
        (= (price Copper Stockholm)    34.0)
        (= (on-sale Copper Stockholm)  10)
        (= (price Footballs Stockholm)    86.0)
        (= (on-sale Footballs Stockholm)  0)
        (= (price Kittens Stockholm)    45.2)
        (= (on-sale Kittens Stockholm)  27)
        (= (price Minerals Stockholm)    10.0)
        (= (on-sale Minerals Stockholm)  60)
        (= (price Gold Stockholm)    36.0)
        (= (on-sale Gold Stockholm)  9)
        (= (price Platinum Stockholm)    62.8)
        (= (on-sale Platinum Stockholm)  5)
        (= (price DVDs Stockholm)    15.2)
        (= (on-sale DVDs Stockholm)  1)
        (= (price TuringMachines Stockholm)    63.2)
        (= (on-sale TuringMachines Stockholm)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Vienna Bonn ) 4.6)
        (= (drive-cost Bonn Vienna ) 4.6)
        (can-drive Vienna Bonn)
        (can-drive Bonn Vienna)
        (= (drive-cost Vienna Copenhagen ) 4.0)
        (= (drive-cost Copenhagen Vienna ) 4.0)
        (can-drive Vienna Copenhagen)
        (can-drive Copenhagen Vienna)
        (= (drive-cost Vienna Stockholm ) 6.8)
        (= (drive-cost Stockholm Vienna ) 6.8)
        (can-drive Vienna Stockholm)
        (can-drive Stockholm Vienna)
        (= (drive-cost Bonn Copenhagen ) 0.8)
        (= (drive-cost Copenhagen Bonn ) 0.8)
        (can-drive Bonn Copenhagen)
        (can-drive Copenhagen Bonn)
        (at camel0    Stockholm)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
