(define (problem marketcount3)
(:domain Trader)
(:objects
            Madrid Paris Hamburg  - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Madrid)    2.0)
        (= (on-sale Food Madrid)  20)
        (= (price ExpensiveRugs Madrid)    5.2)
        (= (on-sale ExpensiveRugs Madrid)  17)
        (= (price Coffee Madrid)    17.6)
        (= (on-sale Coffee Madrid)  23)
        (= (price Cattle Madrid)    2.0)
        (= (on-sale Cattle Madrid)  5)
        (= (price Water Madrid)    19.2)
        (= (on-sale Water Madrid)  30)
        (= (price Cars Madrid)    100.8)
        (= (on-sale Cars Madrid)  0)
        (= (price GummyBears Madrid)    72.8)
        (= (on-sale GummyBears Madrid)  61)
        (= (price Computers Madrid)    100.8)
        (= (on-sale Computers Madrid)  0)
        (= (price LaminateFloor Madrid)    63.6)
        (= (on-sale LaminateFloor Madrid)  0)
        (= (price Copper Madrid)    34.0)
        (= (on-sale Copper Madrid)  10)
        (= (price Footballs Madrid)    86.0)
        (= (on-sale Footballs Madrid)  0)
        (= (price Kittens Madrid)    45.2)
        (= (on-sale Kittens Madrid)  27)
        (= (price Minerals Madrid)    10.0)
        (= (on-sale Minerals Madrid)  60)
        (= (price Gold Madrid)    36.0)
        (= (on-sale Gold Madrid)  9)
        (= (price Platinum Madrid)    62.8)
        (= (on-sale Platinum Madrid)  5)
        (= (price DVDs Madrid)    15.2)
        (= (on-sale DVDs Madrid)  1)
        (= (price TuringMachines Madrid)    63.2)
        (= (on-sale TuringMachines Madrid)  0)

        (= (price Food Paris)    6.0)
        (= (on-sale Food Paris)  10)
        (= (price ExpensiveRugs Paris)    7.2)
        (= (on-sale ExpensiveRugs Paris)  12)
        (= (price Coffee Paris)    23.6)
        (= (on-sale Coffee Paris)  8)
        (= (price Cattle Paris)    12.0)
        (= (on-sale Cattle Paris)  0)
        (= (price Water Paris)    29.2)
        (= (on-sale Water Paris)  5)
        (= (price Cars Paris)    84.8)
        (= (on-sale Cars Paris)  38)
        (= (price GummyBears Paris)    14.8)
        (= (on-sale GummyBears Paris)  0)
        (= (price Computers Paris)    72.8)
        (= (on-sale Computers Paris)  28)
        (= (price LaminateFloor Paris)    51.6)
        (= (on-sale LaminateFloor Paris)  28)
        (= (price Copper Paris)    32.0)
        (= (on-sale Copper Paris)  15)
        (= (price Footballs Paris)    60.0)
        (= (on-sale Footballs Paris)  3)
        (= (price Kittens Paris)    63.2)
        (= (on-sale Kittens Paris)  0)
        (= (price Minerals Paris)    12.0)
        (= (on-sale Minerals Paris)  55)
        (= (price Gold Paris)    38.0)
        (= (on-sale Gold Paris)  4)
        (= (price Platinum Paris)    66.8)
        (= (on-sale Platinum Paris)  59)
        (= (price DVDs Paris)    17.2)
        (= (on-sale DVDs Paris)  0)
        (= (price TuringMachines Paris)    33.2)
        (= (on-sale TuringMachines Paris)  0)

        (= (price Food Hamburg)    2.8)
        (= (on-sale Food Hamburg)  18)
        (= (price ExpensiveRugs Hamburg)    5.6)
        (= (on-sale ExpensiveRugs Hamburg)  16)
        (= (price Coffee Hamburg)    18.8)
        (= (on-sale Coffee Hamburg)  20)
        (= (price Cattle Hamburg)    4.0)
        (= (on-sale Cattle Hamburg)  0)
        (= (price Water Hamburg)    21.2)
        (= (on-sale Water Hamburg)  25)
        (= (price Cars Hamburg)    97.6)
        (= (on-sale Cars Hamburg)  6)
        (= (price GummyBears Hamburg)    61.2)
        (= (on-sale GummyBears Hamburg)  26)
        (= (price Computers Hamburg)    95.2)
        (= (on-sale Computers Hamburg)  0)
        (= (price LaminateFloor Hamburg)    61.2)
        (= (on-sale LaminateFloor Hamburg)  4)
        (= (price Copper Hamburg)    33.6)
        (= (on-sale Copper Hamburg)  11)
        (= (price Footballs Hamburg)    80.8)
        (= (on-sale Footballs Hamburg)  0)
        (= (price Kittens Hamburg)    48.8)
        (= (on-sale Kittens Hamburg)  18)
        (= (price Minerals Hamburg)    10.3)
        (= (on-sale Minerals Hamburg)  59)
        (= (price Gold Hamburg)    36.3)
        (= (on-sale Gold Hamburg)  8)
        (= (price Platinum Hamburg)    63.6)
        (= (on-sale Platinum Hamburg)  3)
        (= (price DVDs Hamburg)    15.6)
        (= (on-sale DVDs Hamburg)  0)
        (= (price TuringMachines Hamburg)    57.2)
        (= (on-sale TuringMachines Hamburg)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Madrid Paris ) 4.0)
        (= (drive-cost Paris Madrid ) 4.0)
        (can-drive Madrid Paris)
        (can-drive Paris Madrid)
        (= (drive-cost Madrid Hamburg ) 4.6)
        (= (drive-cost Hamburg Madrid ) 4.6)
        (can-drive Madrid Hamburg)
        (can-drive Hamburg Madrid)
        (= (drive-cost Paris Hamburg ) 6.1)
        (= (drive-cost Hamburg Paris ) 6.1)
        (can-drive Paris Hamburg)
        (can-drive Hamburg Paris)
        (at camel0    Hamburg)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
