(define (problem marketcount4)
(:domain Trader)
(:objects
            Cardiff London Moscow Rome  - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Cardiff)    6.8)
        (= (on-sale Food Cardiff)  8)
        (= (price ExpensiveRugs Cardiff)    7.6)
        (= (on-sale ExpensiveRugs Cardiff)  11)
        (= (price Coffee Cardiff)    24.8)
        (= (on-sale Coffee Cardiff)  5)
        (= (price Cattle Cardiff)    14.0)
        (= (on-sale Cattle Cardiff)  0)
        (= (price Water Cardiff)    31.2)
        (= (on-sale Water Cardiff)  0)
        (= (price Cars Cardiff)    81.6)
        (= (on-sale Cars Cardiff)  46)
        (= (price GummyBears Cardiff)    3.2)
        (= (on-sale GummyBears Cardiff)  0)
        (= (price Computers Cardiff)    67.2)
        (= (on-sale Computers Cardiff)  42)
        (= (price LaminateFloor Cardiff)    49.2)
        (= (on-sale LaminateFloor Cardiff)  34)
        (= (price Copper Cardiff)    31.6)
        (= (on-sale Copper Cardiff)  16)
        (= (price Footballs Cardiff)    54.8)
        (= (on-sale Footballs Cardiff)  16)
        (= (price Kittens Cardiff)    66.8)
        (= (on-sale Kittens Cardiff)  0)
        (= (price Minerals Cardiff)    12.3)
        (= (on-sale Minerals Cardiff)  54)
        (= (price Gold Cardiff)    38.3)
        (= (on-sale Gold Cardiff)  3)
        (= (price Platinum Cardiff)    67.6)
        (= (on-sale Platinum Cardiff)  57)
        (= (price DVDs Cardiff)    17.6)
        (= (on-sale DVDs Cardiff)  0)
        (= (price TuringMachines Cardiff)    27.2)
        (= (on-sale TuringMachines Cardiff)  0)

        (= (price Food London)    6.0)
        (= (on-sale Food London)  10)
        (= (price ExpensiveRugs London)    7.2)
        (= (on-sale ExpensiveRugs London)  12)
        (= (price Coffee London)    23.6)
        (= (on-sale Coffee London)  8)
        (= (price Cattle London)    12.0)
        (= (on-sale Cattle London)  0)
        (= (price Water London)    29.2)
        (= (on-sale Water London)  5)
        (= (price Cars London)    84.8)
        (= (on-sale Cars London)  38)
        (= (price GummyBears London)    14.8)
        (= (on-sale GummyBears London)  0)
        (= (price Computers London)    72.8)
        (= (on-sale Computers London)  28)
        (= (price LaminateFloor London)    51.6)
        (= (on-sale LaminateFloor London)  28)
        (= (price Copper London)    32.0)
        (= (on-sale Copper London)  15)
        (= (price Footballs London)    60.0)
        (= (on-sale Footballs London)  3)
        (= (price Kittens London)    63.2)
        (= (on-sale Kittens London)  0)
        (= (price Minerals London)    12.0)
        (= (on-sale Minerals London)  55)
        (= (price Gold London)    38.0)
        (= (on-sale Gold London)  4)
        (= (price Platinum London)    66.8)
        (= (on-sale Platinum London)  59)
        (= (price DVDs London)    17.2)
        (= (on-sale DVDs London)  0)
        (= (price TuringMachines London)    33.2)
        (= (on-sale TuringMachines London)  0)

        (= (price Food Moscow)    5.2)
        (= (on-sale Food Moscow)  12)
        (= (price ExpensiveRugs Moscow)    6.8)
        (= (on-sale ExpensiveRugs Moscow)  13)
        (= (price Coffee Moscow)    22.3)
        (= (on-sale Coffee Moscow)  11)
        (= (price Cattle Moscow)    10.0)
        (= (on-sale Cattle Moscow)  0)
        (= (price Water Moscow)    27.2)
        (= (on-sale Water Moscow)  10)
        (= (price Cars Moscow)    88.0)
        (= (on-sale Cars Moscow)  30)
        (= (price GummyBears Moscow)    26.3)
        (= (on-sale GummyBears Moscow)  0)
        (= (price Computers Moscow)    78.3)
        (= (on-sale Computers Moscow)  14)
        (= (price LaminateFloor Moscow)    54.0)
        (= (on-sale LaminateFloor Moscow)  22)
        (= (price Copper Moscow)    32.3)
        (= (on-sale Copper Moscow)  14)
        (= (price Footballs Moscow)    65.2)
        (= (on-sale Footballs Moscow)  0)
        (= (price Kittens Moscow)    59.6)
        (= (on-sale Kittens Moscow)  0)
        (= (price Minerals Moscow)    11.6)
        (= (on-sale Minerals Moscow)  56)
        (= (price Gold Moscow)    37.6)
        (= (on-sale Gold Moscow)  5)
        (= (price Platinum Moscow)    66.0)
        (= (on-sale Platinum Moscow)  61)
        (= (price DVDs Moscow)    16.8)
        (= (on-sale DVDs Moscow)  0)
        (= (price TuringMachines Moscow)    39.2)
        (= (on-sale TuringMachines Moscow)  0)

        (= (price Food Rome)    2.8)
        (= (on-sale Food Rome)  18)
        (= (price ExpensiveRugs Rome)    5.6)
        (= (on-sale ExpensiveRugs Rome)  16)
        (= (price Coffee Rome)    18.8)
        (= (on-sale Coffee Rome)  20)
        (= (price Cattle Rome)    4.0)
        (= (on-sale Cattle Rome)  0)
        (= (price Water Rome)    21.2)
        (= (on-sale Water Rome)  25)
        (= (price Cars Rome)    97.6)
        (= (on-sale Cars Rome)  6)
        (= (price GummyBears Rome)    61.2)
        (= (on-sale GummyBears Rome)  26)
        (= (price Computers Rome)    95.2)
        (= (on-sale Computers Rome)  0)
        (= (price LaminateFloor Rome)    61.2)
        (= (on-sale LaminateFloor Rome)  4)
        (= (price Copper Rome)    33.6)
        (= (on-sale Copper Rome)  11)
        (= (price Footballs Rome)    80.8)
        (= (on-sale Footballs Rome)  0)
        (= (price Kittens Rome)    48.8)
        (= (on-sale Kittens Rome)  18)
        (= (price Minerals Rome)    10.3)
        (= (on-sale Minerals Rome)  59)
        (= (price Gold Rome)    36.3)
        (= (on-sale Gold Rome)  8)
        (= (price Platinum Rome)    63.6)
        (= (on-sale Platinum Rome)  3)
        (= (price DVDs Rome)    15.6)
        (= (on-sale DVDs Rome)  0)
        (= (price TuringMachines Rome)    57.2)
        (= (on-sale TuringMachines Rome)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Cardiff London ) 6.7)
        (= (drive-cost London Cardiff ) 6.7)
        (can-drive Cardiff London)
        (can-drive London Cardiff)
        (= (drive-cost Cardiff Moscow ) 4.2)
        (= (drive-cost Moscow Cardiff ) 4.2)
        (can-drive Cardiff Moscow)
        (can-drive Moscow Cardiff)
        (= (drive-cost Cardiff Rome ) 3.3)
        (= (drive-cost Rome Cardiff ) 3.3)
        (can-drive Cardiff Rome)
        (can-drive Rome Cardiff)
        (= (drive-cost London Rome ) 4.2)
        (= (drive-cost Rome London ) 4.2)
        (can-drive London Rome)
        (can-drive Rome London)
        (at camel0      Rome)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
