(define (problem marketcount2)
(:domain Trader)
(:objects
             Moscow Obeliai - market
        camel0 - camel
        Food ExpensiveRugs Coffee Cattle Water Cars GummyBears Computers LaminateFloor Copper Footballs Kittens Minerals Gold Platinum DVDs TuringMachines - goods)
(:init

        (= (price Food Moscow)    5.2)
        (= (on-sale Food Moscow)  12)
        (= (price ExpensiveRugs Moscow)    6.8)
        (= (on-sale ExpensiveRugs Moscow)  13)
        (= (price Coffee Moscow)    22.3)
        (= (on-sale Coffee Moscow)  11)
        (= (price Cattle Moscow)    10.0)
        (= (on-sale Cattle Moscow)  0)
        (= (price Water Moscow)    27.2)
        (= (on-sale Water Moscow)  10)
        (= (price Cars Moscow)    88.0)
        (= (on-sale Cars Moscow)  30)
        (= (price GummyBears Moscow)    26.3)
        (= (on-sale GummyBears Moscow)  0)
        (= (price Computers Moscow)    78.3)
        (= (on-sale Computers Moscow)  14)
        (= (price LaminateFloor Moscow)    54.0)
        (= (on-sale LaminateFloor Moscow)  22)
        (= (price Copper Moscow)    32.3)
        (= (on-sale Copper Moscow)  14)
        (= (price Footballs Moscow)    65.2)
        (= (on-sale Footballs Moscow)  0)
        (= (price Kittens Moscow)    59.6)
        (= (on-sale Kittens Moscow)  0)
        (= (price Minerals Moscow)    11.6)
        (= (on-sale Minerals Moscow)  56)
        (= (price Gold Moscow)    37.6)
        (= (on-sale Gold Moscow)  5)
        (= (price Platinum Moscow)    66.0)
        (= (on-sale Platinum Moscow)  61)
        (= (price DVDs Moscow)    16.8)
        (= (on-sale DVDs Moscow)  0)
        (= (price TuringMachines Moscow)    39.2)
        (= (on-sale TuringMachines Moscow)  0)

        (= (price Food Obeliai)    2.8)
        (= (on-sale Food Obeliai)  18)
        (= (price ExpensiveRugs Obeliai)    5.6)
        (= (on-sale ExpensiveRugs Obeliai)  16)
        (= (price Coffee Obeliai)    18.8)
        (= (on-sale Coffee Obeliai)  20)
        (= (price Cattle Obeliai)    4.0)
        (= (on-sale Cattle Obeliai)  0)
        (= (price Water Obeliai)    21.2)
        (= (on-sale Water Obeliai)  25)
        (= (price Cars Obeliai)    97.6)
        (= (on-sale Cars Obeliai)  6)
        (= (price GummyBears Obeliai)    61.2)
        (= (on-sale GummyBears Obeliai)  26)
        (= (price Computers Obeliai)    95.2)
        (= (on-sale Computers Obeliai)  0)
        (= (price LaminateFloor Obeliai)    61.2)
        (= (on-sale LaminateFloor Obeliai)  4)
        (= (price Copper Obeliai)    33.6)
        (= (on-sale Copper Obeliai)  11)
        (= (price Footballs Obeliai)    80.8)
        (= (on-sale Footballs Obeliai)  0)
        (= (price Kittens Obeliai)    48.8)
        (= (on-sale Kittens Obeliai)  18)
        (= (price Minerals Obeliai)    10.3)
        (= (on-sale Minerals Obeliai)  59)
        (= (price Gold Obeliai)    36.3)
        (= (on-sale Gold Obeliai)  8)
        (= (price Platinum Obeliai)    63.6)
        (= (on-sale Platinum Obeliai)  3)
        (= (price DVDs Obeliai)    15.6)
        (= (on-sale DVDs Obeliai)  0)
        (= (price TuringMachines Obeliai)    57.2)
        (= (on-sale TuringMachines Obeliai)  0)
        (= (bought Food ) 0)
        (= (bought ExpensiveRugs ) 0)
        (= (bought Coffee) 0)
        (= (bought Cattle ) 0)
        (= (bought Water ) 0)
        (= (bought Cars ) 0)
        (= (bought GummyBears ) 0)
        (= (bought Computers ) 0)
        (= (bought LaminateFloor ) 0)
        (= (bought Copper ) 0)
        (= (bought Footballs ) 0)
        (= (bought Kittens ) 0)
        (= (bought Minerals ) 0)
        (= (bought Gold ) 0)
        (= (bought Platinum ) 0)
        (= (bought DVDs ) 0)
        (= (bought TuringMachines ) 0)
        (= (drive-cost Moscow Obeliai ) 2.6)
        (= (drive-cost Obeliai Moscow ) 2.6)
        (can-drive Moscow Obeliai)
        (can-drive Obeliai Moscow)
        (at camel0      Obeliai)
        (= (cash) 100)
        (= (capacity) 20)
        (= (fuel-used) 0)
	(= (fuel) 7.0)
)
(:goal (and
        (>= (cash) 1000)
))
;(:metric minimize (fuel-used)) 
)
