(define (problem delivery-x-12)
   (:domain delivery)
   (:objects rooma roomb roomc roomd roome - room 
             item26 item25 item24 item23 item22 item21 item20 item19
             item18 item17 item16 item15 item14 item13 item12 item11 item10
             item9 item8 item7 item6 item5 item4 item3 item2 item1 - item 
             bot1 bot2 bot3 - bot
             left1 right1 left2 right2 left3 right3 - arm)
             
   (:init (= (weight item26) 3)
          (= (weight item25) 3)
          (= (weight item24) 2)
          (= (weight item23) 2)
          (= (weight item22) 2)
          (= (weight item21) 2)
          (= (weight item20) 2)
          (= (weight item19) 2)
          (= (weight item18) 1)
          (= (weight item17) 1)
          (= (weight item16) 1)
          (= (weight item15) 1)
          (= (weight item14) 1)
          (= (weight item13) 1)
          (= (weight item12) 1)
          (= (weight item11) 1)
          (= (weight item10) 1)
          (= (weight item9) 1)
          (= (weight item8) 1)
          (= (weight item7) 1)
          (= (weight item6) 1)
          (= (weight item5) 1)
          (= (weight item4) 1)
          (= (weight item3) 1)
          (= (weight item2) 1)
          (= (weight item1) 1)

          (at item26 rooma)
          (at item25 rooma)
          (at item24 rooma)
          (at item23 rooma)
          (at item22 rooma)
          (at item21 rooma)
          (at item20 rooma)
          (at item19 rooma)
          (at item18 rooma)
          (at item17 rooma)
          (at item16 rooma)
          (at item15 rooma)
          (at item14 rooma)
          (at item13 rooma)
          (at item12 rooma)
          (at item11 rooma)
          (at item10 rooma)
          (at item9 rooma)
          (at item8 rooma)
          (at item7 rooma)
          (at item6 rooma)
          (at item5 rooma)
          (at item4 rooma)
          (at item3 rooma)
          (at item2 rooma)
          (at item1 rooma)
          
          (at-bot bot1 rooma)
          (at-bot bot2 rooma)
          (at-bot bot3 rooma)
          (free left1)
          (free right1)
          (free left2)
          (free right2)
          (free left3)
          (free right3)
          (mount left1 bot1)
          (mount right1 bot1)
          (mount left2 bot2)
          (mount right2 bot2)
          (mount left3 bot3)
          (mount right3 bot3)
          
          (door rooma roomb)
          (door roomb roomc)
          (door roomc roomd)
          (door roomd roome)
          (door roome rooma)
          
          (= (current_load bot1) 0)
          (= (load_limit bot1) 6)
          (= (current_load bot2) 0)
          (= (load_limit bot2) 6)
          (= (current_load bot3) 0)
          (= (load_limit bot3) 6)
          (= (cost) 0)
          )
   (:goal (and (at item26 roomb)
               (at item25 roomb)
               (at item24 roomb)
               (at item23 roomb)
               (at item22 roomc)
               (at item21 roomc)
               (at item20 roomc)
               (at item19 roomc)
               (at item18 roomd)
               (at item17 roomd)
               (at item16 roomd)
               (at item15 roomd)
               (at item14 roome)
               (at item13 roome)
               (at item12 roome)
               (at item11 roome)
               (at item10 roome)
               (at item9 roome)
               (at item8 roome)
               (at item7 roome)
               (at item6 roome)
               (at item5 roome)
               (at item4 roome)
               (at item3 roome)
               (at item2 roome)
               (at item1 roome)))
               
               (:metric minimize (cost))
               
)
