(define (problem delivery-x-11-octopus)
   (:domain delivery)
   (:objects rooma roomb - room  
             item24 item23 item22 item21 item20 item19
             item18 item17 item16 item15 item14 item13 item12 item11 item10
             item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
             octopus - bot 
             t1 t2 t3 t4 t5 t6 t7 t8 - arm)
   (:init (= (weight item24) 1)
          (= (weight item23) 1)
          (= (weight item22) 1)
          (= (weight item21) 1)
          (= (weight item20) 1)
          (= (weight item19) 1)
          (= (weight item18) 1)
          (= (weight item17) 1)
          (= (weight item16) 1)
          (= (weight item15) 1)
          (= (weight item14) 1)
          (= (weight item13) 1)
          (= (weight item12) 1)
          (= (weight item11) 1)
          (= (weight item10) 1)
          (= (weight item9) 1)
          (= (weight item8) 1)
          (= (weight item7) 1)
          (= (weight item6) 1)
          (= (weight item5) 1)
          (= (weight item4) 1)
          (= (weight item3) 1)
          (= (weight item2) 1)
          (= (weight item1) 1)

          (at item24 rooma)
          (at item23 rooma)        
          (at item22 rooma)
          (at item21 rooma)
          (at item20 rooma)
          (at item19 rooma)
          (at item18 rooma)
          (at item17 rooma)
          (at item16 rooma)
          (at item15 rooma)
          (at item14 rooma)
          (at item13 rooma)
          (at item12 rooma)
          (at item11 rooma)
          (at item10 rooma)
          (at item9 rooma)
          (at item8 rooma)
          (at item7 rooma)
          (at item6 rooma)
          (at item5 rooma)
          (at item4 rooma)
          (at item3 rooma)
          (at item2 rooma)
          (at item1 rooma)
 
          (at-bot octopus rooma)
          (free t1)
          (free t2)
          (free t3)
          (free t4)
          (free t5)
          (free t6)
          (free t7)
          (free t8)
          (mount t1 octopus)
          (mount t2 octopus)
          (mount t3 octopus)
          (mount t4 octopus)
          (mount t5 octopus)
          (mount t6 octopus)
          (mount t7 octopus)
          (mount t8 octopus)          
          
          (door rooma roomb)
          (door roomb rooma)
          
          (= (current_load octopus) 0)
          (= (load_limit octopus) 8)
          (= (cost) 0)
          )
   (:goal (and (at item24 roomb)
               (at item23 roomb)
               (at item22 roomb)
               (at item21 roomb)
               (at item20 roomb)
               (at item19 roomb)
               (at item18 roomb)
               (at item17 roomb)
               (at item16 roomb)
               (at item15 roomb)
               (at item14 roomb)
               (at item13 roomb)
               (at item12 roomb)
               (at item11 roomb)
               (at item10 roomb)
               (at item9 roomb)
               (at item8 roomb)
               (at item7 roomb)
               (at item6 roomb)
               (at item5 roomb)
               (at item4 roomb)
               (at item3 roomb)
               (at item2 roomb)
               (at item1 roomb)))
               
               (:metric minimize (cost))
               
)
