(define (problem delivery-x-8)
   (:domain delivery)
   (:objects rooma roomb roomc roomd - room 
             item18 item17 item16 item15 item14 item13 item12 item11 item10
             item9 item8 item7 item6 item5 item4 item3 item2 item1 - item 
             bot1 bot2 - bot
             left1 right1 left2 right2 - arm)
             
   (:init (= (weight item18) 1)
          (= (weight item17) 1)
          (= (weight item16) 1)
          (= (weight item15) 1)
          (= (weight item14) 1)
          (= (weight item13) 1)
          (= (weight item12) 1)
          (= (weight item11) 1)
          (= (weight item10) 1)
          (= (weight item9) 1)
          (= (weight item8) 1)
          (= (weight item7) 1)
          (= (weight item6) 1)
          (= (weight item5) 1)
          (= (weight item4) 1)
          (= (weight item3) 1)
          (= (weight item2) 1)
          (= (weight item1) 1)
          
          (at item18 rooma)
          (at item17 rooma)
          (at item16 rooma)
          (at item15 rooma)
          (at item14 rooma)
          (at item13 rooma)
          (at item12 rooma)
          (at item11 rooma)
          (at item10 rooma)
          (at item9 rooma)
          (at item8 rooma)
          (at item7 rooma)
          (at item6 rooma)
          (at item5 rooma)
          (at item4 rooma)
          (at item3 rooma)
          (at item2 rooma)
          (at item1 rooma)
          
          (at-bot bot1 rooma)
          (at-bot bot2 rooma)
          (free left1)
          (free right1)
          (free left2)
          (free right2)
          (mount left1 bot1)
          (mount right1 bot1)
          (mount left2 bot2)
          (mount right2 bot2)
          
          (door rooma roomb)
          (door roomb rooma)
          (door rooma roomc)
          (door roomc rooma)
          (door roomd roomb)
          (door roomb roomd)
          (door roomd roomc)
          (door roomc roomd)
          
          (= (current_load bot1) 0)
          (= (load_limit bot1) 6)
          (= (current_load bot2) 0)
          (= (load_limit bot2) 6)
          (= (cost) 0)
          )
   (:goal (and (at item18 roomd)
               (at item17 roomd)
               (at item16 roomd)
               (at item15 roomd)
               (at item14 roomd)
               (at item13 roomd)
               (at item12 roomc)
               (at item11 roomc)
               (at item10 roomc)
               (at item9 roomc)
               (at item8 roomc)
               (at item7 roomc)
               (at item6 roomb)
               (at item5 roomb)
               (at item4 roomb)
               (at item3 roomb)
               (at item2 roomb)
               (at item1 roomb)))
               
               (:metric minimize (cost))
               
)
