(define (problem delivery-x-7)
   (:domain delivery)
   (:objects rooma roomb roomc roomd - room 
             item16 item15 item14 item13 item12 item11 item10
             item9 item8 item7 item6 item5 item4 item3 item2 item1 - item 
             bot1 bot2 - bot
             left1 right1 left2 right2 - arm)
             
   (:init (= (weight item16) 3)
          (= (weight item15) 3)
          (= (weight item14) 3)
          (= (weight item13) 3)
          (= (weight item12) 2)
          (= (weight item11) 2)
          (= (weight item10) 1)
          (= (weight item9) 1)
          (= (weight item8) 1)
          (= (weight item7) 1)
          (= (weight item6) 1)
          (= (weight item5) 1)
          (= (weight item4) 1)
          (= (weight item3) 1)
          (= (weight item2) 2)
          (= (weight item1) 2)

          (at item16 rooma)
          (at item15 rooma)
          (at item14 rooma)
          (at item13 rooma)
          (at item12 rooma)
          (at item11 rooma)
          (at item10 rooma)
          (at item9 rooma)
          (at item8 rooma)
          (at item7 rooma)
          (at item6 rooma)
          (at item5 rooma)
          (at item4 rooma)
          (at item3 rooma)
          (at item2 rooma)
          (at item1 rooma)
          
          (at-bot bot1 rooma)
          (at-bot bot2 rooma)
          (free left1)
          (free right1)
          (free left2)
          (free right2)
          (mount left1 bot1)
          (mount right1 bot1)
          (mount left2 bot2)
          (mount right2 bot2)
          
          (door rooma roomb)
          (door roomb rooma)
          (door rooma roomc)
          (door roomc rooma)
          (door roomd roomb)
          (door roomb roomd)
          (door roomd roomc)
          (door roomc roomd)
          
          (= (current_load bot1) 0)
          (= (load_limit bot1) 6)
          (= (current_load bot2) 0)
          (= (load_limit bot2) 6)
          (= (cost) 0)
          )
   (:goal (and (at item16 roomd)
               (at item15 roomd)
               (at item14 roomd)
               (at item13 roomd)
               (at item12 roomb)
               (at item11 roomb)
               (at item10 roomb)
               (at item9 roomb)
               (at item8 roomb)
               (at item7 roomb)
               (at item6 roomc)
               (at item5 roomc)
               (at item4 roomc)
               (at item3 roomc)
               (at item2 roomc)
               (at item1 roomc)))
               
               (:metric minimize (cost))
               
)
