(define (problem delivery-x-16)
   (:domain delivery)
   (:objects rooma roomb roomc roomd roome roomf - room  
             item34 item33 item32 item31 item30 item29 item28
             item27 item26 item25 item24 item23 item22 item21 item20 item19
             item18 item17 item16 item15 item14 item13 item12 item11 item10
             item9 item8 item7 item6 item5 item4 item3 item2 item1 - item 
             bot1 bot2 bot3 - bot
             left1 mid1 right1 left2 mid2 right2 left3 mid3 right3 - arm)
             
   (:init (= (weight item34) 1)
          (= (weight item33) 1)
          (= (weight item32) 1)
          (= (weight item31) 1)
          (= (weight item30) 1)
          (= (weight item29) 1)
          (= (weight item28) 1)
          (= (weight item27) 1)
          (= (weight item26) 1)
          (= (weight item25) 1)
          (= (weight item24) 1)
          (= (weight item23) 1)
          (= (weight item22) 1)
          (= (weight item21) 1)
          (= (weight item20) 1)
          (= (weight item19) 1)
          (= (weight item18) 1)
          (= (weight item17) 1)
          (= (weight item16) 1)
          (= (weight item15) 1)
          (= (weight item14) 1)
          (= (weight item13) 1)
          (= (weight item12) 1)
          (= (weight item11) 1)
          (= (weight item10) 1)
          (= (weight item9) 1)
          (= (weight item8) 1)
          (= (weight item7) 1)
          (= (weight item6) 1)
          (= (weight item5) 1)
          (= (weight item4) 1)
          (= (weight item3) 1)
          (= (weight item2) 1)
          (= (weight item1) 1)

          (at item34 roomb)
          (at item33 roomb)
          (at item32 roomb)
          (at item31 roomb)
          (at item30 roomb)
          (at item29 rooma)
          (at item28 rooma)
          (at item27 rooma)
          (at item26 rooma)
          (at item25 rooma)
          (at item24 rooma)
          (at item23 rooma)
          (at item22 rooma)
          (at item21 rooma)
          (at item20 roomc)
          (at item19 roomc)
          (at item18 roomc)
          (at item17 roomc)
          (at item16 roomc)
          (at item15 roomc)
          (at item14 roomc)
          (at item13 roomc)
          (at item12 roomc)
          (at item11 roomc)
          (at item10 roomc)
          (at item9 rooma)
          (at item8 rooma)
          (at item7 rooma)
          (at item6 rooma)
          (at item5 rooma)
          (at item4 rooma)
          (at item3 rooma)
          (at item2 rooma)
          (at item1 rooma)
          
          (at-bot bot1 rooma)
          (at-bot bot2 rooma)
          (at-bot bot3 rooma)
          (free left1)
          (free mid1)
          (free right1)
          (free left2)
          (free mid2)
          (free right2)
          (free left3)
          (free mid3)
          (free right3)
          (mount left1 bot1)
          (mount mid1 bot1)
          (mount right1 bot1)
          (mount left2 bot2)
          (mount mid2 bot2)
          (mount right2 bot2)
          (mount left3 bot3)
          (mount mid3 bot3)
          (mount right3 bot3)
          
          (door rooma roomb)
          (door roomb roomc)
          (door roomc roomd)
          (door roomd roome)
          (door roome rooma)
          (door rooma roomf)
          (door roomf roomd)
          
          (= (current_load bot1) 0)
          (= (load_limit bot1) 10)
          (= (current_load bot2) 0)
          (= (load_limit bot2) 10)
          (= (current_load bot3) 0)
          (= (load_limit bot3) 10)
          (= (cost) 0)
          )
   (:goal (and (at item34 roome)
               (at item33 roome)
               (at item32 roome)
               (at item31 roome)
               (at item30 roome)
               (at item29 roome)
               (at item28 roome)
               (at item27 roome)
               (at item26 roome)
               (at item25 roome)
               (at item24 roomd)
               (at item23 roomd)
               (at item22 roomd)
               (at item21 roomd)
               (at item20 roomd)
               (at item19 roomd)
               (at item18 roomd)
               (at item17 roomd)
               (at item16 roomf)
               (at item15 roomf)
               (at item14 roomf)
               (at item13 roomf)
               (at item12 roomf)
               (at item11 roomf)
               (at item10 roomf)
               (at item9 roomf)
               (at item8 roomb)
               (at item7 roomb)
               (at item6 roomb)
               (at item5 roomb)
               (at item4 roomb)
               (at item3 roomb)
               (at item2 roomb)
               (at item1 roomb)))
               
               (:metric minimize (cost))
               
)
