(define (problem delivery-x-14)
   (:domain delivery)
   (:objects rooma roomb roomc roomd roome roomf - room
             item30 item29 item28
             item27 item26 item25 item24 item23 item22 item21 item20 item19
             item18 item17 item16 item15 item14 item13 item12 item11 item10
             item9 item8 item7 item6 item5 item4 item3 item2 item1 - item 
             bot1 bot2 bot3 - bot
             left1 right1 left2 right2 left3 right3 - arm)
             
   (:init (= (weight item30) 3)
          (= (weight item29) 3)
          (= (weight item28) 3)
          (= (weight item27) 3)
          (= (weight item26) 2)
          (= (weight item25) 2)
          (= (weight item24) 2)
          (= (weight item23) 2)
          (= (weight item22) 1)
          (= (weight item21) 1)
          (= (weight item20) 1)
          (= (weight item19) 1)
          (= (weight item18) 1)
          (= (weight item17) 1)
          (= (weight item16) 1)
          (= (weight item15) 1)
          (= (weight item14) 1)
          (= (weight item13) 1)
          (= (weight item12) 1)
          (= (weight item11) 1)
          (= (weight item10) 1)
          (= (weight item9) 1)
          (= (weight item8) 1)
          (= (weight item7) 1)
          (= (weight item6) 1)
          (= (weight item5) 1)
          (= (weight item4) 1)
          (= (weight item3) 1)
          (= (weight item2) 1)
          (= (weight item1) 1)

          (at item30 rooma)
          (at item29 rooma)
          (at item28 rooma)
          (at item27 rooma)
          (at item26 rooma)
          (at item25 rooma)
          (at item24 rooma)
          (at item23 rooma)
          (at item22 roomb)
          (at item21 roomb)
          (at item20 roomb)
          (at item19 roomb)
          (at item18 roomb)
          (at item17 roomb)
          (at item16 roomb)
          (at item15 roomb)
          (at item14 rooma)
          (at item13 rooma)
          (at item12 rooma)
          (at item11 rooma)
          (at item10 rooma)
          (at item9 rooma)
          (at item8 rooma)
          (at item7 rooma)
          (at item6 rooma)
          (at item5 rooma)
          (at item4 rooma)
          (at item3 rooma)
          (at item2 rooma)
          (at item1 rooma)
          
          (at-bot bot1 rooma)
          (at-bot bot2 rooma)
          (at-bot bot3 rooma)
          (free left1)
          (free right1)
          (free left2)
          (free right2)
          (free left3)
          (free right3)
          (mount left1 bot1)
          (mount right1 bot1)
          (mount left2 bot2)
          (mount right2 bot2)
          (mount left3 bot3)
          (mount right3 bot3)
          
          (door rooma roomb)
          (door roomb roomc)
          (door roomc roomd)
          (door roomd roome)
          (door roome rooma)
          (door rooma roomf)
          (door roomf roomd)
          
          (= (current_load bot1) 0)
          (= (load_limit bot1) 6)
          (= (current_load bot2) 0)
          (= (load_limit bot2) 6)
          (= (current_load bot3) 0)
          (= (load_limit bot3) 6)
          (= (cost) 0)
          )
   (:goal (and (at item30 roome)
               (at item29 roome)
               (at item28 roome)
               (at item27 roome)
               (at item26 roome)
               (at item25 roome)
               (at item24 roome)
               (at item23 roome)
               (at item22 roomb)
               (at item21 roomb)
               (at item20 roomb)
               (at item19 roomb)
               (at item18 roomb)
               (at item17 roomb)
               (at item16 roomb)
               (at item15 roomb)
               (at item14 roomc)
               (at item13 roomc)
               (at item12 roomc)
               (at item11 roomc)
               (at item10 roomc)
               (at item9 roomc)
               (at item8 roomf)
               (at item7 roomf)
               (at item6 roomf)
               (at item5 roomf)
               (at item4 roomf)
               (at item3 roomf)
               (at item2 roomf)
               (at item1 roomf)))
               
               (:metric minimize (cost))
               
)
