(define (problem mprime-x-24)
   (:domain mystery-prime-typed)
   (:objects turkey cherry tofu lettuce bacon chicken muffin
             chocolate pepper shrimp orange apple wurst potato melon - food
             achievement satiety curiosity - pleasure
             grief angina depression sciatica loneliness jealousy
             anxiety boils dread hangover laceration prostatitis abrasion
             anger abrasion-2 jealousy-8 prostatitis-3 anxiety-4
             loneliness-1 angina-16 boils-5 dread-6 laceration-7 hangover-13
             depression-14 grief-15 sciatica-11 anger-12 angina-32 anger-9
             hangover-10 loneliness-31 anxiety-26 abrasion-27 dread-28
             sciatica-29 depression-30 - pain
)
   (:init
(= (harmony satiety) 2)
          (craves anger-9 wurst)
          (eats potato wurst)
          (craves curiosity muffin)
          (craves abrasion-27 melon)
          (craves laceration-7 shrimp)
          (eats lettuce bacon)
          (eats melon potato)
          (eats muffin tofu)
          (eats turkey bacon)


(= (locale shrimp) 1)
          (eats orange shrimp)
          (eats cherry chicken)
(= (locale tofu) 0)
(= (harmony curiosity) 3)
          (eats shrimp apple)

          (craves satiety bacon)
(= (locale lettuce) 4)
          (eats pepper potato)

          (craves hangover chicken)
          (eats wurst potato)
          (craves anger muffin)

          (eats apple shrimp)
          (craves depression-30 melon)
          (eats chocolate apple)
          (eats cherry tofu)
          (craves abrasion chicken)

          (craves boils lettuce)
          (eats tofu muffin)
(= (harmony achievement) 2)
          (craves jealousy-8 pepper)
          (craves grief turkey)
(= (locale chocolate) 4)
(= (locale chicken) 2)
          (craves dread lettuce)
(= (locale apple) 0)
          (craves sciatica-11 apple)
          (craves achievement cherry)
          (craves depression cherry)
          (craves dread-28 melon)
          (eats potato pepper)
(= (locale muffin) 3)

          (eats apple chocolate)
          (craves jealousy lettuce)
          (craves boils-5 shrimp)
          (craves anxiety lettuce)
          (craves anxiety-4 pepper)
          (eats wurst orange)
          (eats turkey chicken)
          (craves angina turkey)
          (eats tofu chicken)
          (eats muffin melon)
(= (locale wurst) 1)
          (eats potato melon)
          (eats chocolate pepper)
          (eats cherry lettuce)
(= (locale potato) 9)
          (eats pepper melon)
          (eats melon pepper)
(= (locale orange) 3)
          (craves anger-12 apple)
          (eats chicken tofu)
          (eats orange wurst)
          (eats muffin apple)
          (craves laceration chicken)

(= (locale melon) 9)
          (eats shrimp orange)
(= (locale bacon) 5)
          (eats melon muffin)
          (eats apple muffin)
          (craves hangover-10 wurst)
          (craves grief-15 orange)
          (eats chicken turkey)


          (craves loneliness tofu)
          (craves loneliness-31 potato)
          (craves sciatica-29 melon)
          (craves prostatitis-3 pepper)
(= (locale turkey) 2)
(= (locale pepper) 9)
          (craves hangover-13 orange)
          (craves abrasion-2 chocolate)
          (craves sciatica tofu)
          (craves depression-14 orange)
          (eats pepper chocolate)
          (eats lettuce cherry)
          (eats bacon lettuce)

(= (locale cherry) 0)
          (craves dread-6 shrimp)
          (craves angina-32 wurst)
          (craves angina-16 shrimp)

          (craves anxiety-26 melon)
          (eats bacon turkey)
          (craves prostatitis chicken)
          (eats tofu cherry)
          (eats chicken cherry)
          (craves loneliness-1 pepper))
   (:goal (and (craves jealousy-8 pepper)
               (craves anxiety-4 pepper)
               (craves anger-12 cherry))))
