(define (problem mprime-x-15)
   (:domain mystery-prime-typed)
   (:objects turkey lamb pea cod chicken cantelope broccoli lemon
             pistachio lobster pepper bacon ham haroset okra cucumber onion
             - food
             curiosity expectation understanding learning satisfaction
             stimulation entertainment satiety lubricity aesthetics empathy
             - pleasure
             anxiety boils anger angina prostatitis laceration depression
             jealousy loneliness hangover grief sciatica dread - pain
)
   (:init

          (eats haroset onion)
          (craves learning broccoli)
          (craves satiety haroset)
          (craves laceration broccoli)
(= (harmony expectation) 3)
          (craves depression broccoli)
          (craves grief bacon)
          (eats bacon ham)
          (eats okra cucumber)
          (eats lemon cod)

          (craves understanding cod)
(= (locale bacon) 4)
(= (locale okra) 3)
          (craves empathy onion)
          (craves curiosity turkey)
(= (locale lobster) 5)
          (eats turkey pea)
          (eats pepper bacon)

          (craves entertainment pepper)
          (craves anxiety turkey)
          (craves prostatitis chicken)
          (eats cod lemon)
          (eats broccoli pistachio)
          (craves angina chicken)
          (eats onion haroset)
(= (harmony learning) 2)
          (eats onion ham)
          (craves expectation lamb)
          (eats pistachio broccoli)
          (eats cantelope turkey)
          (eats cod lamb)

(= (locale cantelope) 4)
          (eats bacon pepper)
          (craves jealousy pistachio)
(= (harmony empathy) 1)
          (eats chicken lamb)
(= (harmony aesthetics) 3)
          (eats lobster ham)
(= (harmony understanding) 1)
          (eats chicken cantelope)
(= (harmony lubricity) 3)
          (eats pea turkey)
          (eats cantelope lamb)
          (eats cucumber okra)
(= (harmony satiety) 3)
          (eats lamb cod)
(= (locale cucumber) 2)
          (craves lubricity okra)
(= (locale broccoli) 3)
(= (locale pistachio) 3)
(= (locale cod) 10)



          (eats pea cod)
(= (locale pea) 4)
          (eats lamb cantelope)
          (eats cantelope chicken)
(= (locale ham) 6)
          (eats haroset lemon)

(= (locale lamb) 6)

          (eats lobster cucumber)
(= (locale haroset) 3)
          (craves anger pea)
          (eats broccoli lemon)
(= (harmony curiosity) 1)
(= (locale pepper) 2)
          (eats lemon haroset)
          (eats haroset pepper)
          (craves aesthetics cucumber)
          (craves stimulation lobster)
          (eats pepper haroset)
          (eats chicken cod)
          (eats turkey cantelope)
          (craves satisfaction pistachio)
          (eats ham lobster)
          (eats pistachio okra)
          (eats okra pistachio)
(= (locale lemon) 5)
(= (locale chicken) 7)
          (eats cod chicken)
          (craves hangover bacon)
          (craves boils pea)
(= (locale turkey) 1)

(= (locale onion) 1)
          (eats ham bacon)
          (eats cucumber lobster)
(= (harmony stimulation) 2)
          (craves sciatica cucumber)

          (eats cod pea)
          (craves loneliness lobster)
          (eats ham onion)
(= (harmony satisfaction) 3)


          (eats lamb chicken)
          (eats lemon broccoli)
          (craves dread onion)
(= (harmony entertainment) 1))
   (:goal (and (craves jealousy chicken))))
