(define (problem mprime-x-26)
   (:domain mystery-prime-typed)
   (:objects pepper papaya flounder endive marzipan haroset turkey
             scallop pistachio snickers hamburger rice - food
             understanding learning entertainment empathy satisfaction
             - pleasure
             depression boils hangover jealousy - pain
)
   (:init
(= (harmony satisfaction) 3)
          (eats haroset hamburger)
          (craves entertainment haroset)
          (eats flounder papaya)
          (eats hamburger haroset)
          (eats rice haroset)
          (eats rice scallop)
(= (locale hamburger) 5)
          (eats marzipan haroset)
          (eats endive haroset)
(= (locale pistachio) 1)
          (eats endive pistachio)
          (eats pepper snickers)
          (eats turkey marzipan)
          (eats haroset marzipan)

(= (harmony entertainment) 1)
          (eats turkey papaya)
(= (locale haroset) 5)
          (eats rice pistachio)

          (eats hamburger marzipan)

          (eats endive rice)
          (eats pepper flounder)
(= (harmony understanding) 1)
          (eats haroset endive)
          (eats papaya flounder)
          (eats pistachio rice)

(= (locale turkey) 4)
(= (locale scallop) 4)
(= (locale snickers) 1)
          (eats papaya turkey)
          (craves satisfaction snickers)
          (eats haroset rice)
          (eats scallop hamburger)
(= (locale marzipan) 0)

          (eats scallop rice)
(= (locale rice) 4)
          (craves depression marzipan)
(= (locale endive) 1)
(= (locale papaya) 1)
          (craves hangover pistachio)
          (eats marzipan hamburger)
          (eats rice endive)
          (craves empathy scallop)

          (craves understanding papaya)
          (eats snickers hamburger)
          (craves learning marzipan)
          (eats hamburger scallop)
(= (harmony empathy) 2)
          (eats flounder pepper)
          (eats pistachio endive)
          (eats pistachio turkey)
          (craves boils haroset)
          (craves jealousy snickers)

(= (locale pepper) 0)
(= (harmony learning) 1)
          (eats turkey pistachio)
          (eats snickers pepper)
          (eats hamburger snickers)
(= (locale flounder) 2)
          (eats marzipan turkey)
)
   (:goal (and (craves boils papaya))))
