(define (problem mprime-x-18)
   (:domain mystery-prime-typed)
   (:objects guava chocolate wonderbread pepper cantelope tofu pea
             rice scallop hotdog lemon cucumber chicken haroset bacon
             potato orange marzipan broccoli wurst endive turkey - food
             entertainment learning curiosity rest triumph expectation
             satisfaction - pleasure
             jealousy prostatitis depression hangover angina anger grief
             boils sciatica - pain
)
   (:init
(= (harmony rest) 1)

          (eats wonderbread guava)

          (eats tofu chocolate)
(= (harmony expectation) 3)
(= (locale cucumber) 7)
          (eats pea cucumber)
          (eats scallop lemon)
          (eats hotdog chicken)

(= (locale rice) 6)
          (eats wonderbread tofu)
          (eats orange marzipan)
          (craves entertainment chocolate)
          (eats scallop chicken)
          (eats chocolate cantelope)
          (eats chocolate tofu)
          (eats pepper cantelope)
(= (harmony entertainment) 3)
(= (locale guava) 4)
          (craves jealousy wonderbread)
          (craves anger broccoli)
          (eats cantelope pepper)

          (eats rice pea)
          (craves triumph bacon)
(= (harmony satisfaction) 2)
          (eats lemon scallop)
          (eats wurst potato)
          (eats potato scallop)
          (eats lemon cucumber)
          (craves angina marzipan)
          (eats potato turkey)
          (eats cucumber lemon)
          (eats wonderbread pea)
          (eats guava pepper)
          (eats scallop potato)
          (eats hotdog lemon)

          (eats haroset wurst)
          (eats turkey potato)
          (eats bacon wurst)
(= (locale hotdog) 0)
          (eats cantelope chocolate)
          (eats hotdog scallop)
          (eats broccoli turkey)
          (eats cucumber pea)
          (eats chicken rice)
          (craves satisfaction turkey)
(= (locale potato) 1)
(= (locale scallop) 0)
          (eats turkey orange)
          (eats pea rice)
          (eats pepper guava)

          (craves prostatitis scallop)
(= (locale chocolate) 2)
(= (locale orange) 0)
          (eats pea wonderbread)
          (eats wurst haroset)
          (craves hangover lemon)

          (eats wurst bacon)
(= (locale tofu) 6)
          (eats chicken hotdog)
(= (locale haroset) 3)
          (eats rice chicken)
          (eats potato wurst)
(= (locale wonderbread) 3)
          (eats haroset endive)
(= (locale pea) 2)
          (craves learning pepper)
          (eats endive haroset)
          (eats marzipan endive)
          (craves rest scallop)
          (eats bacon broccoli)
          (eats turkey broccoli)
          (craves boils endive)
          (craves depression hotdog)
          (eats endive marzipan)
(= (locale endive) 0)

          (eats guava wonderbread)

(= (locale cantelope) 5)
(= (locale bacon) 0)
(= (harmony learning) 1)
          (craves sciatica turkey)
          (eats orange turkey)
(= (locale turkey) 2)
(= (locale lemon) 4)
          (craves curiosity cantelope)
          (eats marzipan orange)
          (craves grief wurst)
(= (locale marzipan) 5)
          (eats chicken scallop)
(= (harmony curiosity) 1)
          (eats broccoli bacon)
(= (harmony triumph) 3)

          (craves expectation potato)
(= (locale broccoli) 2)
          (eats lemon hotdog)
(= (locale pepper) 5)
(= (locale chicken) 1)
(= (locale wurst) 7)
          (eats scallop hotdog)
          (eats tofu wonderbread))
   (:goal (and (craves angina chocolate))))
