(define (problem mprime-x-23)
   (:domain mystery-prime-typed)
   (:objects flounder okra ham papaya cherry scallop pistachio lamb
             sweetroll apple onion haroset lobster chicken beef grapefruit
             hotdog wonderbread bacon - food
             learning understanding satisfaction intoxication empathy
             curiosity triumph - pleasure
             sciatica boils abrasion angina anger anxiety loneliness
             hangover laceration jealousy depression prostatitis grief
             dread boils-2 anxiety-1 - pain
)
   (:init

          (craves learning okra)
          (eats lamb flounder)
          (eats papaya lamb)
          (craves boils-2 grapefruit)
          (craves intoxication onion)
(= (locale okra) 1)
          (craves grief chicken)
(= (locale beef) 1)
          (eats scallop ham)
          (eats sweetroll okra)
          (eats scallop pistachio)
          (craves anxiety-1 wonderbread)
          (eats pistachio apple)
(= (harmony intoxication) 2)
          (eats onion pistachio)
          (craves abrasion ham)
(= (harmony curiosity) 2)
          (eats sweetroll cherry)
          (craves triumph bacon)
          (craves angina papaya)
(= (locale ham) 5)
(= (harmony learning) 1)
(= (locale scallop) 5)
          (craves anger cherry)
          (eats haroset grapefruit)

          (eats bacon lobster)
          (eats grapefruit haroset)
(= (locale lamb) 3)
          (eats bacon haroset)
(= (harmony triumph) 3)
          (eats grapefruit hotdog)
(= (locale wonderbread) 2)
          (eats lobster bacon)
          (eats apple onion)
(= (harmony understanding) 2)
(= (locale onion) 1)
          (craves prostatitis lobster)
          (craves boils okra)
          (craves dread beef)
          (craves jealousy onion)
          (eats pistachio onion)
          (craves loneliness pistachio)
          (eats apple pistachio)
(= (locale sweetroll) 0)
          (eats grapefruit beef)
          (eats papaya ham)
          (eats cherry pistachio)
          (eats hotdog wonderbread)
(= (locale cherry) 3)
(= (locale chicken) 4)
          (craves depression haroset)
(= (locale papaya) 3)
(= (harmony satisfaction) 2)
(= (locale grapefruit) 1)
          (eats chicken beef)
          (eats hotdog chicken)

          (eats hotdog lamb)
          (eats pistachio scallop)
          (craves understanding cherry)
          (craves sciatica flounder)
(= (locale apple) 4)
          (craves hangover sweetroll)
          (eats ham papaya)
          (eats hotdog grapefruit)
          (eats flounder lamb)
          (craves anxiety scallop)
          (eats chicken hotdog)
          (eats onion apple)

          (craves satisfaction lamb)

(= (locale haroset) 4)

(= (locale lobster) 2)
          (eats lamb papaya)
          (craves laceration apple)
          (craves empathy haroset)
          (eats lamb hotdog)
          (eats pistachio cherry)
(= (locale hotdog) 0)
          (eats cherry sweetroll)
          (eats beef lobster)
          (eats lamb okra)
(= (locale flounder) 4)
          (eats lobster beef)
          (eats okra sweetroll)
          (eats beef chicken)

          (eats okra lamb)
          (eats haroset bacon)
          (eats onion flounder)
(= (locale bacon) 4)
          (eats wonderbread bacon)
          (eats ham scallop)
          (craves curiosity grapefruit)

          (eats flounder onion)
(= (harmony empathy) 1)
          (eats beef grapefruit)
          (eats bacon wonderbread)
          (eats wonderbread hotdog)
(= (locale pistachio) 4))
   (:goal (and (craves laceration chicken))))
