(define (problem mprime-x-22)
   (:domain mystery-prime-typed)
   (:objects lettuce marzipan wonderbread onion bacon popover ham
             guava chicken cantelope pepper scallop beef wurst lamb pea
             cherry shrimp hamburger kale muffin - food
             stimulation curiosity triumph understanding expectation
             entertainment intoxication satisfaction aesthetics achievement
             love lubricity rest learning excitement satiety
             - pleasure
             angina grief prostatitis jealousy dread boils hangover anger
             depression loneliness abrasion sciatica laceration anxiety
             dread-2 sciatica-1 hangover-4 abrasion-3 - pain
)
   (:init
(= (harmony satisfaction) 1)
          (craves entertainment chicken)
(= (harmony excitement) 1)
          (eats wurst pea)
(= (harmony curiosity) 2)

(= (harmony triumph) 2)
          (eats beef shrimp)
(= (harmony understanding) 1)
          (eats hamburger cherry)
          (eats guava ham)


          (eats muffin pea)
          (craves intoxication cantelope)
          (eats marzipan wonderbread)
          (eats beef cherry)
          (eats pea lamb)
          (eats lamb shrimp)
(= (locale shrimp) 4)
          (eats scallop beef)
          (eats scallop cantelope)
          (eats cherry scallop)
          (craves anger guava)
          (eats lamb cantelope)
          (craves curiosity bacon)
          (craves dread-2 cherry)
(= (locale cantelope) 3)
          (eats ham guava)
          (eats guava chicken)
          (eats onion bacon)
          (eats marzipan lettuce)
(= (harmony learning) 1)

          (eats wonderbread lettuce)
          (craves achievement beef)
          (eats cherry beef)
(= (locale pepper) 3)
          (eats lamb pepper)
          (eats popover bacon)
          (eats bacon onion)
          (craves love wurst)
          (eats cherry hamburger)
          (eats pepper wurst)

(= (harmony satiety) 2)
          (eats shrimp muffin)
(= (locale wurst) 5)
(= (locale cherry) 0)
(= (locale pea) 5)
          (eats shrimp lamb)
          (craves dread bacon)
          (craves hangover-4 hamburger)
(= (locale chicken) 2)
          (eats pea muffin)
          (craves triumph popover)
          (craves depression pepper)
          (craves rest pea)
          (craves abrasion beef)
          (eats hamburger kale)
          (eats kale wurst)
(= (locale marzipan) 5)
(= (locale wonderbread) 2)
          (eats beef scallop)
          (eats bacon marzipan)
(= (locale ham) 1)
          (eats kale scallop)

          (craves sciatica wurst)
(= (harmony lubricity) 3)
(= (locale hamburger) 2)
          (eats pea wurst)
          (eats pepper lamb)
          (eats wonderbread marzipan)
          (eats lettuce marzipan)
          (eats popover ham)
          (eats scallop hamburger)
          (eats scallop shrimp)
          (craves lubricity lamb)
(= (locale guava) 0)
(= (harmony intoxication) 3)
          (eats kale pepper)
          (craves boils popover)
          (craves learning shrimp)
          (craves abrasion-3 muffin)
          (eats chicken popover)
          (eats lamb pea)
          (eats shrimp beef)
(= (harmony achievement) 1)
          (eats hamburger scallop)
          (craves anxiety pea)
          (eats scallop kale)
          (eats pepper kale)
          (craves satisfaction pepper)
(= (harmony stimulation) 1)
          (eats ham popover)
(= (locale bacon) 5)
          (eats lettuce wonderbread)
          (eats wurst kale)
          (craves hangover ham)
          (eats wurst pepper)
          (eats marzipan bacon)
          (craves laceration lamb)
          (eats cantelope scallop)
          (eats muffin shrimp)
(= (locale onion) 1)
(= (locale popover) 1)
(= (harmony entertainment) 3)
          (craves excitement kale)
          (craves angina lettuce)
(= (harmony expectation) 1)
          (eats chicken cherry)
(= (locale scallop) 2)
(= (locale muffin) 0)
(= (locale lettuce) 3)
          (craves understanding ham)
(= (harmony rest) 1)
          (craves satiety muffin)
          (eats onion lettuce)
          (craves loneliness scallop)
(= (harmony aesthetics) 2)
          (eats chicken guava)
          (craves sciatica-1 shrimp)
(= (harmony love) 2)

          (eats cantelope lamb)
(= (locale lamb) 2)
          (craves grief marzipan)
          (eats bacon popover)
          (eats lettuce onion)
          (eats scallop cherry)
          (eats popover chicken)

          (eats kale hamburger)
          (craves prostatitis wonderbread)
          (craves expectation guava)
          (eats shrimp scallop)
          (craves jealousy onion)
(= (locale kale) 4)
          (eats cherry chicken)
          (craves stimulation lettuce)
(= (locale beef) 1)
          (craves aesthetics scallop))
   (:goal (and (craves hangover lamb))))
