(define (problem mprime-x-19)
   (:domain mystery-prime-typed)
   (:objects bacon tofu lamb lobster beef cantelope onion
             wonderbread lemon haroset marzipan flounder okra snickers ham
             - food
             aesthetics stimulation entertainment achievement lubricity love
             expectation learning - pleasure
             sciatica loneliness laceration grief abrasion anxiety dread
             boils jealousy prostatitis anger hangover depression angina
             - pain
)
   (:init
(= (locale cantelope) 0)
(= (harmony achievement) 2)
(= (harmony love) 1)
(= (locale onion) 0)
          (eats lobster bacon)
          (craves jealousy haroset)
          (craves love haroset)
          (craves sciatica bacon)
          (craves abrasion beef)
          (eats lobster haroset)
          (eats lemon ham)
(= (harmony stimulation) 3)
          (eats wonderbread bacon)
(= (harmony lubricity) 3)
          (craves hangover okra)
          (craves stimulation lamb)
          (eats okra snickers)
(= (locale marzipan) 3)
          (eats beef lemon)
          (eats haroset flounder)
          (eats lemon cantelope)
          (eats marzipan tofu)
(= (harmony expectation) 2)
          (craves dread wonderbread)

          (eats wonderbread okra)
          (eats onion tofu)
          (eats marzipan cantelope)
(= (locale lemon) 1)
(= (locale okra) 1)
          (eats lemon beef)
          (craves angina ham)
          (eats bacon wonderbread)
          (eats okra wonderbread)
          (eats beef lamb)
          (craves laceration lamb)
          (eats lamb beef)
          (eats wonderbread marzipan)
          (eats snickers wonderbread)
(= (locale lobster) 1)
          (eats haroset lamb)
          (craves loneliness tofu)
(= (locale bacon) 1)
          (eats tofu marzipan)
          (eats marzipan wonderbread)
          (craves lubricity lemon)
          (eats cantelope lemon)
          (eats beef marzipan)
(= (locale haroset) 1)

          (craves depression snickers)
          (eats bacon lobster)

          (eats lamb haroset)
          (eats snickers okra)
          (eats flounder ham)

(= (locale beef) 3)
          (craves anger flounder)
(= (locale lamb) 5)
(= (harmony entertainment) 1)

(= (harmony learning) 2)

          (craves anxiety onion)
          (eats cantelope marzipan)
          (craves learning snickers)
(= (harmony aesthetics) 3)
(= (locale flounder) 3)
          (eats ham lemon)
          (craves grief lobster)
          (eats marzipan beef)
(= (locale ham) 5)
(= (locale wonderbread) 0)
(= (locale tofu) 1)
          (craves expectation okra)
          (craves achievement wonderbread)
          (eats haroset lobster)
(= (locale snickers) 1)


          (eats onion snickers)
          (eats flounder haroset)
          (craves boils lemon)
          (eats wonderbread snickers)
          (eats tofu onion)
          (eats snickers onion)
          (craves prostatitis marzipan)
          (craves aesthetics bacon)
          (eats ham flounder)
          (craves entertainment lobster))
   (:goal (and (craves abrasion lobster))))
