(define (problem mprime-x-14)
   (:domain mystery-prime-typed)
   (:objects pea chocolate lobster potato hotdog baguette wurst
             bacon scallion yogurt shrimp flounder papaya cod scallop
             lettuce lemon ham pistachio mutton cucumber - food
             triumph curiosity excitement achievement learning rest
             intoxication love aesthetics - pleasure
             laceration hangover grief sciatica dread loneliness abrasion
             jealousy anger angina anxiety depression anger-1 laceration-2
             prostatitis boils anxiety-3 prostatitis-4 grief-6 depression-7
             jealousy-8 sciatica-15 dread-16 abrasion-5 angina-12 boils-13
             loneliness-14 jealousy-32 grief-9 anger-10 hangover-11 sciatica-28
             boils-29 angina-30 depression-31 laceration-26 hangover-27
             prostatitis-23 loneliness-24 anxiety-25 dread-22 grief-19 angina-20
             abrasion-21 - pain
)
   (:init
(= (harmony love) 2)
(= (harmony rest) 2)
          (craves sciatica-15 shrimp)
(= (locale shrimp) 3)
          (craves depression-7 yogurt)
          (eats bacon scallion)
(= (locale cod) 1)
          (eats pea hotdog)
(= (locale scallop) 5)
          (eats lemon cucumber)
(= (harmony excitement) 3)
          (eats hotdog pea)
          (craves aesthetics cucumber)
          (craves jealousy potato)
          (eats flounder yogurt)
          (craves boils bacon)
          (eats papaya cod)
          (craves laceration-2 bacon)
          (craves grief-6 yogurt)
(= (locale papaya) 3)
          (eats hotdog lobster)
          (eats chocolate wurst)

(= (locale baguette) 5)
(= (locale potato) 2)
          (eats yogurt shrimp)
          (craves angina-30 lettuce)
          (eats scallion shrimp)
          (eats papaya scallion)
(= (locale lobster) 5)
(= (locale chocolate) 2)
(= (harmony intoxication) 3)
          (eats lettuce pistachio)

          (craves anxiety-3 scallion)
          (craves intoxication ham)
          (craves laceration pea)
          (craves rest scallop)
          (eats mutton cucumber)

          (craves loneliness-14 flounder)
          (craves depression wurst)
          (eats shrimp scallion)
          (craves anxiety hotdog)
          (eats bacon yogurt)
          (craves anger-1 bacon)
          (craves loneliness-24 pistachio)
          (eats cod shrimp)
          (craves laceration-26 ham)

          (eats pistachio lettuce)
          (craves triumph pea)
          (craves grief-19 cucumber)
(= (locale wurst) 1)
          (eats shrimp potato)
(= (harmony achievement) 2)
          (craves abrasion-5 shrimp)
          (eats scallop lettuce)
          (craves sciatica chocolate)
          (eats potato pea)
          (craves hangover-27 ham)
          (eats lemon scallop)
          (craves abrasion lobster)
          (craves anger-10 papaya)
          (eats lettuce mutton)
          (eats baguette chocolate)
          (eats scallion scallop)
          (eats ham cucumber)
          (craves love mutton)
(= (locale flounder) 2)
          (craves dread-16 shrimp)
          (eats scallion papaya)
          (craves dread lobster)
          (craves prostatitis-4 scallion)
          (eats scallop baguette)
          (craves curiosity chocolate)
          (eats potato wurst)
          (eats scallop lemon)
          (eats yogurt bacon)
          (eats yogurt flounder)
(= (harmony triumph) 1)
(= (locale mutton) 0)
          (eats shrimp yogurt)
          (craves boils-13 flounder)
          (craves prostatitis bacon)
          (eats scallion bacon)
(= (locale yogurt) 3)
          (craves angina-12 flounder)
          (craves jealousy-8 yogurt)
          (craves loneliness lobster)

(= (locale bacon) 1)
          (craves grief-9 papaya)
          (craves grief chocolate)
          (craves angina potato)
          (eats mutton pistachio)
          (eats lemon ham)
          (eats mutton lettuce)

          (eats scallop scallion)
(= (locale lemon) 2)
          (craves angina-20 cucumber)

(= (locale hotdog) 5)
          (eats mutton lemon)
          (craves boils-29 lettuce)
          (craves hangover chocolate)
          (eats flounder scallion)
(= (locale cucumber) 2)
          (eats wurst potato)
(= (harmony curiosity) 2)
(= (locale pea) 4)
          (eats lettuce scallop)
          (craves jealousy-32 papaya)
          (eats lemon mutton)
          (craves sciatica-28 lettuce)
          (eats lobster baguette)
          (eats potato shrimp)
          (craves abrasion-21 cucumber)
          (eats baguette scallop)
(= (locale lettuce) 2)
          (eats ham lemon)
          (eats shrimp cod)
          (craves learning yogurt)
          (eats baguette lobster)
(= (locale ham) 5)
          (eats scallion flounder)
          (eats cucumber mutton)
          (eats pea potato)
(= (harmony aesthetics) 3)
(= (harmony learning) 3)
          (eats cucumber ham)

          (craves anxiety-25 pistachio)
          (eats lobster hotdog)
          (eats wurst chocolate)
          (craves hangover-11 papaya)
(= (locale pistachio) 1)
          (craves achievement potato)
          (eats chocolate baguette)
          (craves anger potato)
          (craves prostatitis-23 pistachio)
          (craves depression-31 lettuce)
          (eats cod papaya)
          (eats pistachio mutton)
          (eats cucumber lemon)
          (craves excitement lobster)
(= (locale scallion) 3)
          (craves dread-22 mutton))
   (:goal (and (craves prostatitis-23 potato)
               (craves anxiety-25 potato))))
