(define (problem mprime-x-20)
   (:domain mystery-prime-typed)
   (:objects mutton cod muffin tuna pork sweetroll yogurt
             wonderbread turkey pepper rice guava potato orange baguette
             scallion marzipan cherry - food
             love curiosity aesthetics empathy satisfaction triumph
             intoxication lubricity expectation understanding achievement
             - pleasure
             dread abrasion grief laceration - pain
)
   (:init
(eats pepper guava)
(= (locale yogurt) 8)
          (eats turkey guava)
          (craves triumph yogurt)
(= (harmony love) 1)
          (craves abrasion wonderbread)
(= (locale pork) 2)
(= (locale guava) 7)
          (eats marzipan cod)
          (eats yogurt tuna)
(= (locale cod) 7)
          (eats cherry turkey)

(= (locale tuna) 8)
          (eats turkey tuna)
          (eats pork cod)
(= (harmony intoxication) 2)
          (eats turkey cherry)


(= (locale marzipan) 5)
(= (harmony achievement) 2)
          (craves dread yogurt)


          (eats turkey rice)
          (eats cod tuna)
(= (locale potato) 10)
          (craves intoxication wonderbread)
(= (harmony empathy) 1)

(= (locale orange) 2)
          (eats orange scallion)
          (eats pepper cherry)
          (eats mutton pork)
          (eats cod pork)
          (eats marzipan orange)
          (eats baguette guava)
(= (locale pepper) 11)
          (eats rice potato)
(= (locale turkey) 3)
          (eats rice turkey)
          (eats sweetroll tuna)


          (craves expectation orange)
          (eats yogurt muffin)
          (eats marzipan cherry)
(= (harmony lubricity) 3)
          (eats potato scallion)
          (eats tuna turkey)
          (eats tuna cod)
(= (harmony triumph) 2)
          (eats scallion orange)
          (eats muffin sweetroll)
(= (locale wonderbread) 6)
(= (locale scallion) 10)
          (craves grief turkey)
(= (locale mutton) 2)
(= (locale cherry) 7)
          (eats muffin yogurt)
(= (harmony aesthetics) 1)
          (eats yogurt wonderbread)
          (eats sweetroll muffin)
          (eats tuna sweetroll)
          (eats scallion potato)
          (eats baguette rice)
          (eats cherry pepper)
          (eats pork mutton)
          (eats potato rice)
          (craves achievement cherry)
          (eats sweetroll pork)
          (eats tuna yogurt)
          (craves understanding marzipan)
          (eats orange marzipan)

          (craves curiosity cod)


(= (locale muffin) 8)
          (eats wonderbread yogurt)
          (eats guava baguette)
          (craves empathy pork)
(= (locale rice) 0)
(= (harmony expectation) 2)

          (eats guava pepper)
(= (harmony satisfaction) 2)
          (eats pork sweetroll)
          (eats wonderbread mutton)
          (craves satisfaction sweetroll)
(= (locale baguette) 2)
          (eats rice baguette)
(= (locale sweetroll) 7)
          (craves aesthetics muffin)
          (eats cod marzipan)

          (craves laceration cherry)
(= (harmony curiosity) 1)
          (craves lubricity rice)
          (craves love mutton)
          (eats mutton wonderbread)
          (eats guava turkey)

          (eats cherry marzipan)
(= (harmony understanding) 1))
   (:goal (and (craves abrasion pepper))))
